### ISSUE TITLE
Relax dependency on `sassc`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#100]
`sassc` is now in 2.0.1, but we are unnecessarily restraining it to:

```ruby
spec.add_dependency "sassc", "~> 1.12.1"
```

in `isodoc.gemspec`.

This task is to relax and test again a newer version. This is necessary to stop the installation of the deprecated `sass` gem. (https://github.com/metanorma/metanorma-build-scripts/issues/6)

**Comment by opoudjis** [comment]
You're not going to be seeing any gem release in Metanorma until Andrej has updated all Relaton gems.

**Comment by opoudjis** [comment]
Confirmed against metanorma-standoc and metanorma-iso

**Comment by ronaldtse** [comment]
Thank you @opoudjis !
