### ISSUE TITLE
Do not use ISBN identifiers to cross-reference books

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#105]
In general: books and journals, and other such textual content, must not use document identifiers when generating crossreferences for them.

**Comment by opoudjis** [comment]
When that is done, remove the docidentifiers from NIST rendering rspec.

**Comment by ronaldtse** [comment]
@opoudjis why is this?

**Comment by opoudjis** [comment]
There are monographs in the rspec of NIST right now, because that is possible. They are being cited in the body of the text by ISBN, which is of course silly, but is the only thing the stack currently supports.

**Comment by opoudjis** [comment]
@zoras I am assigning this task to you. It's a simple task (now, because i've done some refactoring since I first wrote the ticket):

* In the isodoc gem, isodoc/lib/isodoc/function/references.rb, a document can be cited by its bibitem/docidentifier, unless that identifier is of type DOI. That can never be used.
* At the moment, if a document has an identifier of type ISSN or ISBN, it will be used. That too can never be allowed to happen.
* You will need to write a test case for that.
* Once you have implemented that change, you will see that a testcase in the metanorma-nist gem changes behaviour: A book is currently being cited by its ISBN within text: it's the "formats a non-NIST reference: book". We expect that citation to revert to using the other provided identifier in the bibliographic entry.

I will be available to answer questions, but we need to work out a time we are both on. :-)

For your sanity: check out *all* the following gems into your working directory. You will need to hop between them.

isodoc
metanorma-acme					
metanorma-cli					
metanorma-csand					
metanorma-csd					
metanorma-gb					
metanorma-iec					
metanorma-iso					
metanorma-itu					
metanorma-m3d					
metanorma-mpfd
metanorma-nist
metanorma-ogc
metanorma-rsd
metanorma-sample
metanorma-standoc
metanorma-unece
metanorma-vsd

The dependency chart of gems is on: https://github.com/metanorma/metanorma/issues/54
