### ISSUE TITLE
Refactor all gems' HTML stylesheets to extract common core

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#112]
To mitigate maintenance. Would return common core CSS as a function in isodoc, and potentially override it with local CSSs afterwards.

This involves going through a dozen CSS files, and extracting their common classes into a file. I'd like to delegate this task to @pierrefortier, but I'll do it myself if that isn't possible.

**Comment by opoudjis** [comment]
Pierre, given that you authored the CSS to begin with, are you free to do this task? If so, I will send you a bundle of all the CSS files to refactor.

**Comment by opoudjis** [comment]
[forAnton.zip](https://github.com/metanorma/isodoc/files/3481751/forAnton.zip)

**Comment by strogonoff** [comment]
Do you think it’s better to have common styling as a bunch of (possibly parametrized) mixins, and let each flavor use those mixins as they see fit, passing params as required?

**Comment by strogonoff** [comment]
That’d be one way to refactor that nicely

**Comment by opoudjis** [comment]
I don't think it is necessary: there is a very large amount of CSS that is completely common between them, and occasionally there are new classes specific to flavours. It would be easier for me to maintain if we just have common CSS file, and flavour specific files. You will find some recurring theme colours in the CSS within each flavour gem, true, but they aren't as high a priority for me to factor out.

**Comment by strogonoff** [comment]
OK, after quick 1:1 with Nick the approach is:

- Do a basic refactoring pass, splitting things that repeat everywhere into one-two common stylesheets
- If there is a place where a mixin with arguments will have a lot of sense, confirm with Nick and do it
- Deliver files with explanation
- Nick will integrate new “common” SCSS files & test to ensure no regressions in appearance

**Comment by strogonoff** [comment]
@opoudjis could you do the following?

- Download the archive attached: [export.zip](https://github.com/metanorma/isodoc/files/3489596/export.zip)

- Apply files & test that there are no visual regressions

This is a first pass of splitting out some of the reset functionality.

**Comment by strogonoff** [comment]
I’m looking to confirm that there’re no regressions, and if not we’ll proceed in similar fashion

**Comment by opoudjis** [comment]
Doing a visual diff on each flavour, with single CSS against refactored CSS.

Acme
CSAND
CSD
GB Compliant
GB
IEC
ISO Human
ISO
ITU
M3D
MPFD
NIST
OGC
RSD
SAMPLE
UNECE
VSD

**Comment by opoudjis** [comment]
Attaching the files which look different.

[GBcompliant.zip](https://github.com/metanorma/isodoc/files/3492071/GBcompliant.zip)

**Comment by strogonoff** [comment]
Thanks, looking into it

**Comment by opoudjis** [comment]
As you're refactoring, could you please fix

````
writing-mode:tb-rl;
````

to 

````
writing-mode:vertical-rl;
````

**Comment by strogonoff** [comment]
Can do, but to be safe and avoid unrelated regressions we’ll probably deal with migration as-is first!

**Comment by opoudjis** [comment]
OK, don't worry about it, I'll do it afterwards.

**Comment by strogonoff** [comment]
@opoudjis 

- Could you run another round of tests with [export.zip](https://github.com/metanorma/isodoc/files/3497433/export.zip)?

- Could you give HTML examples, like the one sent before, for all flavors? To reduce the need for your involvement during regression testing.

**Comment by opoudjis** [comment]
[files.zip](https://github.com/metanorma/isodoc/files/3505373/files.zip)

**Comment by opoudjis** [comment]
All files look the same, although my testing method does not end up using the styles idiosyncratic to each flavour's cover page (as I injected the stylesheets into a compiled ISO document.) I request that you do testing of your own with the bundle of compiled documents attached above.

**Comment by opoudjis** [comment]
@strogonoff Status update?

**Comment by strogonoff** [comment]
Will attach updated files once it’s refactored & tested

**Comment by strogonoff** [comment]
@opoudjis files in the archive are these `htmlstyle.scss`, right? https://github.com/metanorma/metanorma-csand/blob/master/lib/isodoc/csand/html/htmlstyle.scss

**Comment by opoudjis** [comment]
Yes, the files are htmlstyle.scss, except where I broke that convention because there are multiple HTML stylesheets. So:

metanorma-acme/lib/isodoc/acme/html/htmlstyle.scss
metanorma-csand/lib/isodoc/csand/html/htmlstyle.scss
metanorma-csd/lib/isodoc/csd/html/htmlstyle.scss
metanorma-gb/lib/isodoc/gb/html/htmlcompliantstyle.scss
metanorma-gb/lib/isodoc/gb/html/htmlstyle.scss
metanorma-iec/lib/isodoc/iec/html/htmlstyle.scss
metanorma-iso/lib/isodoc/iso/html/style-human.scss
metanorma-iso/lib/isodoc/iso/html/style-iso.scss
metanorma-itu/lib/isodoc/itu/html/htmlstyle.scss
metanorma-m3d/lib/isodoc/m3d/html/htmlstyle.scss
metanorma-mpfd/lib/isodoc/mpfd/html/htmlstyle.scss
metanorma-nist/lib/isodoc/nist/html/htmlstyle.scss
metanorma-ogc/lib/isodoc/ogc/html/htmlstyle.scss
metanorma-rsd/lib/isodoc/rsd/html/htmlstyle.scss
metanorma-sample/lib/isodoc/sample/html/htmlstyle.scss
metanorma-unece/lib/isodoc/unece/html/htmlstyle.scss
metanorma-vsd/lib/isodoc/vsd/html/htmlstyle.scss

**Comment by ronaldtse** [comment]
Looks like we do need some cleanup here 🤣  Thank you @strogonoff !

**Comment by opoudjis** [comment]
... Eh, no. Those files will ALL remain in place; Anton is just extracting their common content.

**Comment by ronaldtse** [comment]
@strogonoff please apply your cleanup ability generously. I'm sure @opoudjis won't mind things being cleaner and more understandable. Iteratively but positively, of course. Thanks.

**Comment by strogonoff** [comment]
@ronaldtse I’m treating this as purely mechanical work. Not sure it’s the best use of my time, but I see that there’s no other choice.

**Comment by strogonoff** [comment]
@opoudjis in which gem can I place the base SCSS/mixins, so that they are importable in all of the above stylesheets? Some gem on which all others depend. After looking at gemspecs, it might be the `isodoc` gem?

**Comment by strogonoff** [comment]
I intend to try to enable all Metanorma flavor gems to “see” SCSS files from `isodoc` by feeding `Gem.loaded_specs['isodoc'].full_gem_path` into `load_paths` Sass configuration property. (If you use Node during build, there also may be other routes available.)

**Comment by ronaldtse** [comment]
This is not just mechanical, but requires expertise and experience in SCSS which we believe you are the best person to do it RIGHT. 

Anyway, the isodoc gem is where the base SCSS should go to because that’s the base for rendering code.

**Comment by ronaldtse** [comment]
Personally I consider this “surgery” :wink:

**Comment by strogonoff** [comment]
I will do my best to ensure the patient doesn’t wake up with wrong limbs in unexpected places

**Comment by ronaldtse** [comment]
:rofl:

**Comment by strogonoff** [comment]
* Post-refactor CSD htmlstyle.scss is down to 402 LoC, from 657 originally. Still a lot, but much of the styling is unfortunately not shared across flavors.
* isodoc’s base styles are ~350 lines.
* isodoc’s styles can be imported in any flavor via `@import ‘base_style/all’`.

Some of the base styling is implemented as plain rules, and will be applied on import. Other styling is implemented as mixins, so after import it still requires application.

Support for relative imports in flavor stylesheets was added, so now you can e.g. split blocks from htmlstyle.scss into separate files, and import them inside htmlstyle.scss (CSD does this with `_coverpage.scss`).

cc @opoudjis @ronaldtse

**Comment by opoudjis** [comment]
[rice.zip](https://github.com/metanorma/isodoc/files/3675872/rice.zip)

I've generated the following. It's different from its predecessor, although because the stakes are low, and because I may have tweaked the file in the interim, I'm not that fussed. But notice that one of the side bands is illegible, because of poor contrast between band background and text.  That is a problem: look at the bands colours more carefully.

[rice.old.html.zip](https://github.com/metanorma/isodoc/files/3675874/rice.old.html.zip)

**Comment by opoudjis** [comment]
This is the other file I had lying around, from the start of the year. To prevent confusion, I'm doing a before and after with the current gem. They look identical.

[csd-digital-addresses.zip](https://github.com/metanorma/isodoc/files/3675893/csd-digital-addresses.zip)

OK, proceed, just look carefully at the bands: with white lettering, there should be no silver or light grey or white bands (as in the current rice.html output). And... I'm not a fan of the mixins, but I understand the need for them. But all other things being equal, the fewer mixins, the better.

**Comment by strogonoff** [comment]
@opoudjis As far as lettering, I believe there should be no changes, did you spot any?

If current version is more or less a success, I’ll try to limit and phase out mixin use in future, and apply more styles by default on import.

**Comment by strogonoff** [comment]
> I may have tweaked the file in the interim

Yeah, it seems like this archive (rice.zip) is not the latest pre-refactor version, so I guess it’s a non-issue? Here is what I see in your upload:

<img width="1352" alt="Screen Shot 2019-10-02 at 1 39 45 PM" src="https://user-images.githubusercontent.com/292959/66020629-428da400-e51a-11e9-8537-b0506233ef52.png">

The band on the left is unreadable, and there are a couple of other issues

Here is a screenshot from the sample doc I generated from latest _pre-refactor_ version of Metanorma-CSD and mn-samples-cc:

<img width="1352" alt="Screen Shot 2019-10-02 at 1 40 09 PM" src="https://user-images.githubusercontent.com/292959/66020664-618c3600-e51a-11e9-9cca-3cb6d8c48c6a.png">

**Comment by opoudjis** [comment]
@strogonoff I am about to migrate pseudocode from NIST and ITU to all of Metanorma; so it will need to be added to the isodoc base class. Please use ITU as the baseline rendering; the background shading of pseudocode needs to be the same as for sourcecode.

**Comment by opoudjis** [comment]
Actually, I'll create the base class: but the mixin of pseudocodeBlock needs to be propagated to all flavours, just like sourceBlock.

**Comment by opoudjis** [comment]
There are 17 HTML stylesheets.

Refactoring to date has been done on 5:

metanorma-csd/lib/isodoc/csd/html/htmlstyle.scss:@import 'base_style/all';
metanorma-gb/lib/isodoc/gb/html/htmlstyle.scss:@import 'base_style/all';
metanorma-itu/lib/isodoc/itu/html/htmlstyle.scss:@import 'base_style/all';
metanorma-nist/lib/isodoc/nist/html/htmlstyle.scss:@import 'base_style/all';
metanorma-ogc/lib/isodoc/ogc/html/htmlstyle.scss:@import 'base_style/all';

Work must (MUST) be done on the remaining 12. This is holding back further refactoring.

I will make tickets for the remaining 12 stylesheets.
