### ISSUE TITLE
Relaton ISO refererences need em-dash

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#118]
Title parts are being connected in Word output with hyphen, not em-dash.

> ISO 216, Writing paper and certain classes of printed matter - Trimmed sizes - A and B series, and indication of machine direction

**Comment by opoudjis** [comment]
Can't replicate in new document. Checking ISO 690 again, where this first occurred.

**Comment by opoudjis** [comment]
Replicated, for ISO 3166-1.

**Comment by opoudjis** [comment]
The title is being joined up using - instead of ndash in relaton-iso-bib.

**Comment by opoudjis** [comment]
But! Most ISO titles are *not* being split; e.g. ISO 639-1:

`<title type="title-main" format="text/plain" language="en" script="Latn">Codes for the representation of names of languages ?~@~T Part 1: Alpha-2 code</title>`

That looks to be a bug.

**Comment by opoudjis** [comment]
ISO is using actual en-dash, as well as `--`, to delimit titles. Fixing.

**Comment by ronaldtse** [comment]
Thanks @opoudjis , @andrew2net could you add specs for this?

**Comment by andrew2net** [comment]
@ronaldtse yes I can

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by opoudjis** [comment]
I've updated all impacted rspecs
