### ISSUE TITLE
Asciimath failing to render on Windows (?)

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#125]
The attached minimal document, containing a single AsciiMath formula, renders acceptably on Mac:

[math.adoc.zip](https://github.com/metanorma/isodoc/files/3668348/math.adoc.zip)
[math.mac.zip](https://github.com/metanorma/isodoc/files/3668349/math.mac.zip)

It is not rendering at all on Windows, in @manuel489 's enviromment:

![image](https://user-images.githubusercontent.com/1911039/65842425-c2770b00-e36e-11e9-8b2b-fbd3e03cf207.png)

Manuel's environment is correctly converting the AsciiMath input into MathML, but the MathML is not rendering.

This suggests something has gone wrong in Manuel's environment. Could someone try and replicate?

Manuel will also try this out on Linux.

**Comment by opoudjis** [comment]
Issue is restricted to HTML for Manuel, so this could be just issue with MathJax.

**Comment by manuel489** [comment]
Hello, I have compiled (math.adoc) in both Windows and Linux and got the same result. Just as it's shown in Nick's attached image.

**Comment by manuel489** [comment]
I attach the compiling results from both OS for better reference.
[math-results.zip](https://github.com/metanorma/isodoc/files/3668939/math-results.zip)

**Comment by opoudjis** [comment]
I see it fine. This means that you, Manuel, can't access MathJax, and I can.

This then becomes a different issue, one of the global accessibility of the MathJax script...

**Comment by ronaldtse** [comment]
This goes back to making the output packaged on deliverables without relying on Internet access.

**Comment by opoudjis** [comment]
Which is well and good, but Manuel needs a solution now...

**Comment by opoudjis** [comment]
I'm saying we find an alternate site.

**Comment by opoudjis** [comment]
False alarm: this was only an issue with Chrome failing to invoke external scripts.

**Comment by ronaldtse** [comment]
@opoudjis then can we close this now?
