### ISSUE TITLE
Boldface isn't rendering in table environment (HTML output)

### ISSUE THREAD

**Issue by manuel489** [metanorma/isodoc#149]
The following markup:
````
[%unnumbered]
[cols="a,a"]
|===
^h|Header 1 ^h|Header 2

|*This text should be bold*
|*This text should be bold*
|===
````

Renders in HTML as:

![capture6](https://user-images.githubusercontent.com/33627611/68472444-f4458200-01f6-11ea-86bf-15e81058994e.JPG)

Sample file:
[table-boldface-issue.zip](https://github.com/metanorma/mn-templates-iso/files/3824286/table-boldface-issue.zip)

**Comment by opoudjis** [comment]
I am fixing this only in the base CSS of isodoc and in metanorma-iso: we are in the middle of refactoring HTML CSS, and I'm not going to redundantly add it to other gems whose stylesheets are about to disappear.
