### ISSUE TITLE
Duplicated footnotes

### ISSUE THREAD

**Issue by anermina** [metanorma/isodoc#155]
Footnotes which are referenced more than once are numbered differently and described each time.

original:
![image](https://user-images.githubusercontent.com/55683568/69383919-3bce1280-0cbb-11ea-866d-dd0338e89e32.png)

rendered:
![image](https://user-images.githubusercontent.com/55683568/69383943-48eb0180-0cbb-11ea-8dcb-ae1dca5fddef.png)

[footnotes_res.zip](https://github.com/metanorma/metanorma-itu/files/3877149/footnotes_res.zip)

**Comment by opoudjis** [comment]
I've done it. Need to add note to metanorma.com that these repeat footnotes are realised as fields in Word, so you will need to do Update Fields on first opening the document (as you already have to do for Table of Contents.)
