### ISSUE TITLE
Implement ISO 690 citations and references: A.4 Named tag system

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#161]
A.4 Named tag system

A.4.1 Citation in text

A named tag chosen by the author is given to every cited information resource. When citing an information resource, a named tag enclosed in parentheses, brackets or superscript, placed after the cited information, represents a citation to the specified information resource.

All citations of a particular information resource utilize an identical named tag. If particular parts of an information resource are cited, page numbers, etc., may be given after the named tag.

EXAMPLE	The notion of an invisible college has been explored in the sciences [INV]. Its absence among historians is noted by Stieg [HISTNEEDS, p.556]. It may be, as Burchard [HUMLIB] points out, that they have no assistants, or are reluctant to delegate [PROBISH] [BLRDRPT]. The collaborative relationships required by such groups have been recently codified as an International Standard [ISO44001].

A.4.2 References

A.4.2.1 General

The references to the information resources should be arranged in an alphabetical order according to the named tags.

A.4.2.2 Example reference list with named tags

EXAMPLE	…
[BLRDRPT] CHAPMAN, J. Report to the British Library Research and Development Department [microfiche]. Birmingham: University School of History, 1981. S1/9/281.
…
[HISTNEEDS] STIEG, M. F. The information needs of historians. College and Research Libraries, 1981, 42(6), 549–560.
[HUMLIB] BURCHARD, J. E. How humanists use a library. In: C. F. J. OVERHAGE and J. R. HARMAN (eds.). Intrex: Report on a planning conference and information transfer experiments. Cambridge, Mass.: MIT Press, 3 Sept. 1965, pp. 41–87.
[INV] CRANE, D. Invisible Colleges. Chicago: University of Chicago Press, 1972.
[ISO44001] INTERNATIONAL ORGANIZATION FOR STANDARDIZATION. ISO 44001:2017 Collaborative business relationship management systems — Requirements and framework. Geneva: International Organization for Standardization.
…
[PROBISH] SMITH, C. Problems of information studies in history. In: S. STONE (ed.), Humanities information research. Sheffield: CRUS, 1980, pp. 27–30.

**Comment by opoudjis** [comment]
This has been implemented as Metanorma named identifiers: https://github.com/metanorma/metanorma-standoc/issues/159, https://github.com/metanorma/metanorma-standoc/issues/232
