### ISSUE TITLE
Implement ISO 690 citations and references: A.6 Implied system and "the ISO system"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#163]
A.6 Implied system

A.6.1 Citation in text

The implied system works with citing information resources with document identifiers, such as International Standards. Since not all information resources are labelled with document identifiers, the implied system is often used in conjunction with any other citation system.
When citing an information resource, the information resource’s document identifier is used directly in text. There is no difference in citing an information resource once or multiple times. If particular parts of an information resource are cited, page numbers, etc., may be given after the document identifier.

EXAMPLE	The notion of an invisible college has been explored in the sciences [26]. Its absence among historians is noted by Stieg [13 p. 556]. It may be, as Burchard [8] points out, that they have no assistants, or are reluctant to delegate [27, 28]. The collaborative relationships required by such groups have been recently codified as an International Standard, ISO 44001:2017. A successful example of such collaboration can be found in IETF RFC 3113.

A.6.2 References

A.6.2.1 General

When only the implied system is used, information resources should be arranged in a logical order according to the document identifiers. Appearance of information resources may be grouped by and ordered according to category.

A.6.2.2 Using the implied system with other citation systems

In addition to the ordering guidance that applies when the implied system is used independently, when in use with other citation systems:
—	implicitly cited information resources may be ordered according to rules of the other system; 
—	implicitly cited information resources may be grouped together as desired; and 
—	references of the different citation systems may be placed in separate bibliographies. 

NOTE	In standardization documents, the implied system is often used together with another citation system, with references split into separate bibliographies.

A.6.2.3 Example reference list exclusively using implied system

EXAMPLE	…
ISO 8601-1:2019, Date and time — Representations for information interchange — Part 1: Basic rules
ISO 8601-2:2019, Date and time — Representations for information interchange — Part 1: Basic rules
CC 18012, Date and time — General recurrence representation
IETF RFC 3339, Date and Time on the Internet: Timestamps
NIST SP 800-90B, Recommendation for the Entropy Sources Used for Random Bit Generation

A.6.2.4 Example reference list using the implied system with another system

EXAMPLE	…
[2] ISO 44001:2017, Collaborative business relationship management systems — Requirements and framework.
[3] IETF RFC 3113, 3GPP-IETF Standardization Collaboration.
…
[8] BURCHARD, J. E. How humanists use a library. In: C. F. J. OVERHAGE and J. R. HARMAN (eds.). Intrex: Report on a planning conference and information transfer experiments. Cambridge, Mass.: MIT Press, 3 Sept. 1965, pp. 41–87.
…
[13] STIEG, M. F. The information needs of historians. College and Research Libraries, 1981, 42(6), 549–560.
…
[26] CRANE, D. Invisible Colleges. Chicago: University of Chicago Press, 1972.
[27] SMITH, C. Problems of information studies in history. In: S. STONE (ed.), Humanities information research. Sheffield: CRUS, 1980, pp. 27–30.
[28] CHAPMAN, J. Report to the British Library Research and Development Department [microfiche]. Birmingham: University School of History, 1981. S1/9/281.

**Comment by opoudjis** [comment]
Already in place as the Metanorma default; the alternate system is by default numeric, but name tags can also be used. Sorting is flavour specific, but mostly does indeed rely on document identifiers.
