### ISSUE TITLE
Integrate XSL:FO PDF rendering

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#167]
Waiting on @manuel489 and @anermina to identify all discrepancies between DOC and PDF output, and @Intelligent2013 to resolve them all.

**Comment by manuel489** [comment]
Ok @opoudjis , I'm working on it.

**Comment by opoudjis** [comment]
Given what you guys are finding, I'm assuming this is going to be at least a month. I need to do significant refactoring too, since a lot of stuff done in isodoc now needs to be done in asciidoctor.

**Comment by opoudjis** [comment]
Applies to: NIST ISO IEC UNECE ITU

**Comment by opoudjis** [comment]
acme (rsd/vsd will be included here), csand m3d mpfd will get generic stylesheet. csd, ogc will get distinct stylesheets. This ticket only closes when all of those created.
