### ISSUE TITLE
Internationalise requirement metadata labels

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#172]
Need:

* Obligation
* Subject
* Inherit (or Inherits From or Dependency)

**Comment by opoudjis** [comment]
@ronaldtse Please provide Mandarin

**Comment by ronaldtse** [comment]
Is this for ITU or GB?

**Comment by ronaldtse** [comment]
义务
主体
继承 （继承自 / 依属关系）

**Comment by opoudjis** [comment]
It's the generic code about requirements, so it's intended for both GB and ITU, unless there's an override.

Thanks; I'll go for "inherits from", 继承自
