### ISSUE TITLE
Rendering of user ids in bibliographies

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#183]
When user id (number) is provided alongside a standard identifier, the rendering is not quite right:

For

````
* [[[dss,(2)NIST FIPS 186]]], Digital Signature Standard (DSS), FIPS Pub 186 (www.itl.nist.gov/div897/pubs/fip186.htm)
````

Normative references gives:

````
<p id="dss" class="NormRef">[2], <i>Digital Signature Standard (DSS)</i></p> 
````

and Bibliography gives

````
<p id="dss" class="Biblio">[4]&#xA0; 4, <i>Digital Signature Standard (DSS)</i></p>
````

What's happening is that the user-supplied identifier is completely displacing the original identifier.

In both cases, I am assuming that the original identifier needs to appear as well, before the title; in the case of the Bibliography, instead? What was your intent in encoding this in IHO S-63?

**Comment by ronaldtse** [comment]
I think the encoding just means a numbered reference tag is to be used with auto fetch enabled.

**Comment by opoudjis** [comment]
Right, but numbered tags are only appropriate for bibliographies, and they should not be displacing identifiers in normative references (OR bibliographies). In fact, had the encoding left the tags alone and this was treated as an informative bibliography, no number tagging would have been necessary.

**Comment by ronaldtse** [comment]
Got it. But -- how about normative references that do not have document identifiers? Those ought to be referenced by numbers right?

**Comment by opoudjis** [comment]
yes.

**Comment by opoudjis** [comment]
Rationalised: if there is both a user ID and a non-user ID in the bibliography, give both universally.
