### ISSUE TITLE
Ability to provide multiple sources using [.source] attribute

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#186]
_Originally: https://github.com/metanorma/mn-samples-nist/issues/19_

In NIST 800-53r4, there are some terms (in the Glossary section) whose definitions are provided using multiple sources. For example:
![image](https://user-images.githubusercontent.com/55683568/79896944-4aa32780-8409-11ea-8a3c-bcc18e401803.png)

Is there a possibility to provide multiple sources using one `[.source]` attribute?

For the example given above, I used two `[.source]` attributes in order to include both references, which resulted in following:
![image](https://user-images.githubusercontent.com/55683568/79897199-a5d51a00-8409-11ea-834a-31c4605b82e5.png)

Moreover, in this example can be seen that the source is written below the term in the original document, unlike in the generated one.

**Comment by opoudjis** [comment]
Data entry should remain the same as it is now, multiple sources each on their own para (so that we get distinct termsource tags); it is output's job to put them in a single line.

**Comment by ronaldtse** [comment]
@opoudjis can we have documentation on metanorma.com for this? Thanks.
