### ISSUE TITLE
Separation of Requirement models and their rendering templates in different flavors

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#200]
The issue of metanorma/metanorma-iso#295 is to render an OGC requirement model inside an ISO document. 

To solve this, we will separate the notions of a Requirement model vs its rendering template to the presentation layer.

The goal is to allow usage of any implemented requirement models in any flavor, and allow different rendering of the same requirement model in different flavors.

Currently, there are two requirements models:
1. Metanorma generic requirement
2. OGC requirement

From now on, each requirement will need to be instantiated according to a requirement model class, e.g.:
```
[requirement,type=ogc]
...
```
(if the requirement model is not specified but the document flavor has a default requirement model, e.g. in an OGC document, the model should default to the OGC requirement model).

In the semantic to presentation rendering of a requirement model (in isodoc), we will allow the author to specify how a model is rendered. e.g. an OGC requirement inside an ISO document may use the OGC or ISO rendering.

Since we do not have an ISO rendering for an OGC requirement, we have agreed to utilize the OGC requirement rendering for OGC requirement models in ISO documents as a default.

If there is a need in ISO for an alternative rendering for the OGC requirements model, we can implement a separate rendering template for the "ISO rendering of a OGC requirement".

This supersedes metanorma/metanorma-iso#295.

**Comment by ronaldtse** [comment]
cc: @rggibb this is the ticket that will resolve metanorma/metanorma-iso#295 .

**Comment by opoudjis** [comment]
Realising through mn-requirements gem

**Comment by opoudjis** [comment]
As part of this refactoring:

[ ] metanorma-standoc default model code moves to mn-requirements
[ ] metanorma-standoc methods needed for metanorma-standoc default model code  moves to metanorma-utils, to avoid recursive dependencies
[ ] isodoc default model HTML/DOC rendering code moves to Presentation XML
[ ] isodoc default model Presentation XML moves to mn-requirements
[ ] metanorma-ogc Modspec model Metanorma code moves to mn-requirements
[ ] metanorma-ogc Modspec model Isodoc code moves to mn-requirements

**Comment by opoudjis** [comment]
Problem I still have to work out: how much of the rendering of requirements is flavour-specific, how much is model-specific? All requirements in OGC should be tabular, not just Modspec, for example. The hyperlinking of tests to requirements, OTOH, is Modspec-specific.

**Comment by opoudjis** [comment]
We will default with the entirety of the rendering being done in the gem.

**Comment by opoudjis** [comment]
Will need to insist that the model of all requirements be an attribute: Asciidoctor parser needs to be able to see the model of the requirement immediately. So model cannot be embedded within the metadata definition list.

**Comment by opoudjis** [comment]
Have realised that in OGC, recommendation parts were being cross-referenced without including the identifier of the parent recommendation.

**Comment by opoudjis** [comment]
`:requirements-model:` will override the default model for the flavour.
