### ISSUE TITLE
Nokogiri version needs bumping

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/isodoc#297]
See: https://github.com/advisories/GHSA-7rrm-v45f-jp64

It should also unblock https://github.com/metanorma/metanorma-ietf/issues/150

Upgrading nokogiri to [1.11.0](https://nokogiri.org/CHANGELOG.html#1110-2021-01-03)+ would require dropping support for Ruby 2.4, of which [official support ended on 2020-04-05](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/).

**Comment by opoudjis** [comment]
@ribose-jeffreylau The upgrade to Nokogiri 1.11 is being blocked by https://github.com/metanorma/packed-mn , which requires Ruby 2.4 to function. Until such time as that dependency is resolved, no attempt to upgrade to Nokogiri 1.11 can be accepted.

**Comment by ronaldtse** [comment]
The particular ticket where the Ruby upgrade is being worked on: https://github.com/metanorma/ruby-packer/issues/9

**Comment by ronaldtse** [comment]
@ribose-jeffreylau by any chance is this blocking your workflow?

**Comment by ribose-jeffreylau** [comment]
@opoudjis Noted. Thanks!

@ronaldtse It's not blocking any workflow.  It's just part of the process to resolve dependabot alerts.

**Comment by ronaldtse** [comment]
Got it. Thanks @ribose-jeffreylau !

**Comment by ribose-jeffreylau** [comment]
Closed by b3ca5bb41d01c7dc057d2843130494d9eeb07a70.
