### ISSUE TITLE
fontist breaking new isodoc rspec

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#301]
A new test in isodoc involves running metanorma collection compilation. As a result, some GHA instances are failing, because fontist is not getting the option to run without explicit approval. 

https://github.com/metanorma/isodoc/pull/282/checks?check_run_id=2765931848

The test is in spec/isodoc/sectionsplit_spec.rb. I have tried to put in a mock to force acceptance of fontist, but it does not seem to have worked:

````
  def mock_render
    original_add = ::Metanorma::CollectionRenderer.method(:render)
    allow(::Metanorma::CollectionRenderer)
      .to receive(:render) do |col, opts|
      original_add.call(col, opts.merge(no_install_fonts: true))
    end
  end
````

**Comment by CAMOBAP** [comment]
Done, please check https://github.com/metanorma/isodoc/commit/71ba7ff596acecdcd8e707feaf23189daaa04849

**Comment by opoudjis** [comment]
Been asked to comment. This worked. Closing ticket.
