### ISSUE TITLE
Loose and strict validation

### ISSUE THREAD

**Issue by ribose-jeffreylau** [metanorma/isodoc#314]
Relevant line in build log: https://github.com/CalConnect/csd-transcription-systems/runs/3043780696?check_suite_focus=true#step:5:550

The above seems to cause the expected `*.presentation.xml` to not build, thus failing to output subsequent PDF / HTML / DOC files.  (Strangely enough, the process exited with `0`.)

Only happens after `isodoc` has been upgraded from `1.6.7.*` to `1.7.0`.

**Comment by opoudjis** [comment]
Pull current standoc and isodoc gems from github, those issues have likely been remedied already there.

**Comment by ribose-jeffreylau** [comment]
Thanks @opoudjis .  I found the culprit.  The error is due to missing definition of a referenced term.

This line of error got lost in the sea of other logs: https://github.com/CalConnect/csd-transcription-systems/runs/3043780696?check_suite_focus=true#step:5:438

In this case, one of the ways to fix it is just changing `terms:[languages]` to `terms:[language]` but then it breaks the English grammar, since it should read "_languages_" in the context of the sentence.
Or, amend it to `terms:[language]s` but it'll be rendered as "_language_(3.2)s"  which looks odd.

The standard practice (pun intended) in this case seems to be "_languages_(3.2)", but I'm not sure how it can be achieved with metanorma.

In general, I think `metanorma-cli` should bail as soon as it hits an error like the above, instead of continuing and returning `0`.  And then informative error messages can follow (might be a separate issue though).

cc @ronaldtse

**Comment by ribose-jeffreylau** [comment]
Perhaps I've been doing it wrong?  Maybe the solution is just

```asciidoc
_languages_ (<<term-language>>)
```

Anyway, the suggestion that the CLI should fail fast still stands.

**Comment by ronaldtse** [comment]
The new "concepts mention" functionality is now available:
https://www.metanorma.org/blog/2021-07-06/concepts-in-metanorma/

The actual failure is due to the plural form not being found by Metanorma.

In this case, we should use:

```
{{language,languages}}
```

**Comment by opoudjis** [comment]
The macro is `term:[]`, not `terms[]`, as a synonym of `{{ }}`.

When you enter a `term:[]` reference to a missing string, the error message 

`AsciiDoc Input: (XML Line 000039): Error: Term reference in `term[fred]` missing:                 "fred" is not defined in document`

is generated, and added to the error log *.err, which is output to disk; the document also contains, at the place where the incorrect anchor was located, the text:

> term fred not resolved via ID fred

The error messages are, in fact, informative. While it is easy for me to abort on finding an unresolved anchor, I do not at all agree that execution should abort: being able to see a generated document containing clear error messages is going to be far more helpful in debugging, I have found, than going through an error log. Will not action without go-ahead from @ronaldtse.

**Comment by ribose-jeffreylau** [comment]
> The error messages are, in fact, informative. While it is easy for me to abort on finding an unresolved anchor, I do not at all agree that execution should abort: being able to see a generated document containing clear error messages is going to be far more helpful in debugging, I have found, than going through an error log.

Thanks @opoudjis , that's a fair point.

Instead of aborting, would returning a non-zero exit status work?  That serves to signal that the build is not error-free, and will not erroneously let CI pipelines march ahead with errors still in the document.

**Comment by ronaldtse** [comment]
I agree that a non-zero exit status should apply on any type of error, being consistent with metanorma/metanorma-cli#89, metanorma/metanorma-cli#151, metanorma/metanorma-cli#164 among others.

**Comment by ribose-jeffreylau** [comment]
Having `--strict` `--loose` sounds it might work.

**Comment by opoudjis** [comment]
That's going to take some juggling of metanorma (and the individual gems within it), and rearchitecting. I'm making it medium priority, and I'd much rather @abunashir work on it...

**Comment by opoudjis** [comment]
Error priorities have now been implemented, 0, 1, 2, with 0 currently fatal.
