### ISSUE TITLE
Enable code syntax highlighting in PDF

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#374]
MN2PDF now supports code syntax highlighting. We need to enable it with a command line option as described in
https://github.com/metanorma/mn2pdf/issues/108#issuecomment-1020998649

The place to implement this seems to be here:
https://github.com/metanorma/isodoc/blob/1de30b7e72d8c2aa4438411977fed1a9e02e47a3/lib/isodoc/xslfo_convert.rb#L56-L67

```sh
$ java -Xss5m -Xmx2048m -jar mn2pdf-1.41.jar --xml-file ... --syntax-highlight
```

@CAMOBAP can you help with this? Thanks!

**Comment by CAMOBAP** [comment]
PR is ready for review
