### ISSUE TITLE
emf2svg is now at 1.4.2, unlock from 1.3

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#397]
emf2svg has fixed a critical bug with EMF conversion:
https://github.com/metanorma/emf2svg-ruby/issues/30

Can we unlock from 1.3? The previous version lock was due to Mac arm64 platform issues, but those have been fixed in 1.4.1 (https://github.com/metanorma/emf2svg-ruby/issues/18).

**Comment by ronaldtse** [comment]
This issue is blocking https://github.com/metanorma/isodoc/issues/397. Once this is resolved, https://github.com/metanorma/isodoc/issues/397 can be merged.

**Comment by opoudjis** [comment]
Is pending in https://github.com/metanorma/isodoc/pull/393/files. Release is not for another week.

**Comment by ronaldtse** [comment]
Thanks!
