### ISSUE TITLE
i18n for titles hard-coded in XSLT

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/isodoc#400]
These resources currently hard-coded in the XSLT modules. It would be better move them into gems:

- current value `table_of_contents` is `Table of contents`, but some SDO use another titles:
   - `Contents` - CSD, IHO, MPFD, OGC, UNECE
   - `Table of Contents` - CSA, M3AAWG, NIST, OGC White Paper

- `Descriptors` on the last page of ISO document:
![image](https://user-images.githubusercontent.com/5559926/167267543-175c3986-70e3-4a70-b296-6c07c83fc1d0.png)

- current value for `toc_figures` is `List of figures, for `toc_tables` is `List of tables`, but ITU and OGC (in bookmarks) uses `List of Figures` and `List of Tables`. It is possible to redefine it for ITU and OGC?

- the same relates to `toc_recommendations: List of recommendations`, but in OGC `List of Recommendations`

- in OGC White-paper: consolidated list of tables and figures displayed under the title 'Table of Figures'. It is possible add the resource `table_of_figures`?

- add for ITU - `Summary` - title for abstract with `@id=_summary`.

- Table's continue:
   -  `continued` - en
   - `continué` - fr
   - `продолжение` - ru

- `Voting begins on` and `Voting terminates on` for ISO.

- `Submission Date`, `Approval Date`, `Publication Date`, `Author`, `Editor`, `Contributor` for OGC.
- `Title`, `PROPOSED STABILITY DATE`, `Note from TC/SC officers` for IEC

**Comment by opoudjis** [comment]
These should indeed be internationalised in the Presentation XML. Let me know where they are not.

**Comment by Intelligent2013** [comment]
@opoudjis I've double checked in the resulted presentation xml and there are missing.

> - current value `table_of_contents` is `Table of contents`, but some SDO use another titles:
>   - `Contents` - CSD, IHO, MPFD, OGC, UNECE

Current values:
CSD
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```
IHO:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```
MRFD:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```
OGC:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```
UNECE:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```


>   - `Table of Contents` - CSA, M3AAWG, NIST, OGC White Paper

CSA:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```

M3AAWG:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```

NIST:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```

OGC White Paper:
```xml
<localized-string key="table_of_contents" language="en">Table of contents</localized-string>
```

> - `Descriptors` on the last page of ISO document:

missing in xml.

> - current value for `toc_figures` is `List of figures, for `toc_tables` is `List of tables`, but ITU and OGC (in bookmarks) uses `List of Figures` and `List of Tables`. It is possible to redefine it for ITU and OGC?

Current values in ITU:
```xml
<localized-string key="toc_figures" language="en">List of figures</localized-string>
<localized-string key="toc_tables" language="en">List of tables</localized-string>
```

OGC:
```xml
<localized-string key="toc_figures" language="en">List of figures</localized-string>
<localized-string key="toc_tables" language="en">List of tables</localized-string>
```

> - the same relates to `toc_recommendations: List of recommendations`, but in OGC `List of Recommendations`

OGC:
```xml
<localized-string key="toc_recommendations" language="en">List of recommendations</localized-string>
```

> - in OGC White-paper: consolidated list of tables and figures displayed under the title 'Table of Figures'. It is possible add the resource `table_of_figures`?

`Table of Figures` is missing in OGC xml.

> - add for ITU - `Summary` - title for abstract with `@id=_summary`.

`Summary` is missing in ITU xml.

> - Table's continue:
>   -  `continued` - en
>   - `continué` - fr
>   - `продолжение` - ru

Missing in xml.

> - `Voting begins on` and `Voting terminates on` for ISO.

Missing in ISO xml.

> - `Submission Date`, `Approval Date`, `Publication Date`, `Author`, `Editor`, `Contributor` for OGC.

Missing in OGC xml.

> - `Title`, `PROPOSED STABILITY DATE`, `Note from TC/SC officers` for IEC


Missing in IEC xml.

**Comment by opoudjis** [comment]
> These resources currently hard-coded in the XSLT modules. It would be better move them into gems:

> * current value `table_of_contents` is `Table of contents`, but some SDO use another titles:
>   
>   * `Contents` - CSD, IHO, MPFD, OGC, UNECE
>   * `Table of Contents` - CSA, M3AAWG, NIST, OGC White Paper

Already done for IHO, OGC. Done.

> * `Descriptors` on the last page of ISO document:
>   ![image](https://user-images.githubusercontent.com/5559926/167267543-175c3986-70e3-4a70-b296-6c07c83fc1d0.png)

Seems to be doing the same job as "keywords", but ok. Translating, so in French it will be Descripteur. Added plural under inflection.{i18n word}.pl, so inflection.Descripteur.pl = Descripteurs

> * current value for `toc_figures` is `List of figures, for `toc_tables`is`List of tables`, but ITU and OGC (in bookmarks) uses `List of Figures`and`List of Tables`. It is possible to redefine it for ITU and OGC?

Done

> * the same relates to `toc_recommendations: List of recommendations`, but in OGC `List of Recommendations`

Done

> * in OGC White-paper: consolidated list of tables and figures displayed under the title 'Table of Figures'. It is possible add the resource `table_of_figures`?

Done. I was not aware that was happening, and I'm going to pretend I didn't hear that as a requirement for Word.

> * add for ITU - `Summary` - title for abstract with `@id=_summary`.

Um, I already had Summary as the global equivalent of "abstract" in ITU. I will update ITU code to output Summary only under that condition.

> * Table's continue:
>   
>   * `continued` - en
>   * `continué` - fr
>   * `продолжение` - ru

Done, "continued"

> * `Voting begins on` and `Voting terminates on` for ISO.

voting_begins_on, voting_terminates_on

> * `Submission Date`, `Approval Date`, `Publication Date`, `Author`, `Editor`, `Contributor` for OGC.

````
submission_date: Submission Date
approval_date: Approval Date
publication_date: Publication Date
author: Author
editor: Editor
contributor: Contributor
````


> * `Title`, `PROPOSED STABILITY DATE`, `Note from TC/SC officers` for IEC

````
title: Title
proposed_stability_date: PROPOSED STABILITY DATE
tc_sc_note: Note from TC/SC officers
````

**Comment by opoudjis** [comment]
With the most recent refactor of relaton-render, the `editor` value added here clashes with the `editor` sg, pl abbreviation ("ed.", "eds") used for citations. The two need to be differentiated. We have already had to deal with this clash in ITU, and the resolution is to make "Editor" be `editor_full` in YAML, not `editor`. 

I am moving editor to editor_full. @Intelligent2013 I need you to change

````
xsl:call-template name="getLocalizedString">
                                                                                                        <xsl:with-param name="key">editor</xsl:with-param>
                                                                                                </xsl:call-template><xsl:text>: </xsl:text>
````

to 


````
xsl:call-template name="getLocalizedString">
                                                                                                        <xsl:with-param name="key">editor</xsl:with-param>
                                                                                                </xsl:call-template><xsl:text>: </xsl:text>
````

in all the XSLT. I will do so manually for the release.

**Comment by opoudjis** [comment]
relaton-render should be picking up inflection from a grammar field, as is done elsewhere; but this issue would still obtain.

**Comment by Intelligent2013** [comment]
OGC XSLT updated for `editor_full` i18n.
