### ISSUE TITLE
(URGENT) gem release of private gems failed due to broken rake CSS generation task

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#403]
All private gem pushes to GitHub packages are failing due to this:

https://github.com/metanorma/metanorma-nist/runs/6454462062?check_suite_focus=true
```
git add ~
lib/isodoc/nist/html/_coverpage.css
lib/isodoc/nist/html/htmlstyle.css
lib/isodoc/nist/html/nist.css
lib/isodoc/nist/html/nist_cswp.css
lib/isodoc/nist/html/wordstyle.css
lib/isodoc/nist/html/wordstyle_cswp.css
fatal: /home/runner: '/home/runner' is outside repository at '/home/runner/work/metanorma-nist/metanorma-nist'
rake aborted!
Command failed with status (128): [git add ~...]
/home/runner/work/metanorma-nist/metanorma-nist/vendor/bundle/ruby/2.7.0/gems/isodoc-2.1.1/lib/isodoc/gem_tasks.rb:56:in `block in git_cache_compiled_files'
/home/runner/work/metanorma-nist/metanorma-nist/vendor/bundle/ruby/2.7.0/gems/isodoc-2.1.1/lib/isodoc/gem_tasks.rb:55:in `git_cache_compiled_files'
/home/runner/work/metanorma-nist/metanorma-nist/vendor/bundle/ruby/2.7.0/gems/isodoc-2.1.1/lib/isodoc/gem_tasks.rb:34:in `block in install'
/home/runner/work/metanorma-nist/metanorma-nist/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
Tasks: TOP => build => build_scss
(See full trace by running task with --trace)
```

Notice that the command is trying to `git add` the entire home directory, which causes the failure.

This code is the generation of CSS from SCSS located here:
https://github.com/metanorma/isodoc/blob/main/lib/isodoc/gem_tasks.rb#L54-L64

1. Clearly the `CLEAN` constant is probably not meant to be used this way. I suspect this entire file should be rewritten.
2. This code SHOULD NOT directly call `sh "git ..."`.
3. There is a typo for `notify_borken_compilation` should have been `notify_broken_compilation`.

Given the information on this post:
https://stackoverflow.com/questions/27303575/what-is-the-right-way-to-use-clean-rake-task

We know that `CLEAN` is a Rake FileList. It is meant to store the files/paths that are to be cleaned, NOT retain the CSS file paths.

If we wanted to add the generated CSS paths, use another FileList or just an Array at this line:
https://github.com/metanorma/isodoc/blob/d95a3f9a1f5d42cb476d2f931e7e125522718760/lib/isodoc/gem_tasks.rb#L132

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/isodoc/pull/406 - merged
