### ISSUE TITLE
Inkscape not installing for OSX on GHA, Ruby 3.1

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#414]
https://github.com/metanorma/isodoc/runs/6749891806?check_suite_focus=true

**Comment by CAMOBAP** [comment]
Reproduces unstable 

I noted that other users faced with this for other packages and looks like it more related to runner setup (infrastructure issue) https://github.com/actions/runner/issues/1456#issuecomment-995548843

Looks like `HOMEBREW_CASK_OPTS to "--no-quarantine"` should help

**Comment by CAMOBAP** [comment]
Workaround applied
