### ISSUE TITLE
PresentationXML will include div

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#425]
As part of https://github.com/metanorma/isodoc/issues/200, I'm changing the encoding of requirements, so that they will mostly be done in Presentation XML: the Presentation XML will contain `<requirement/recommendation/permission>`, but all their children will be elements already familiar from elsewhere in Metanorma: you will no longer have to support the tags

"inherit", "description", "specification", "measurement-target", "verification", "import", "component"

However, instead, I am introducing `<div>` as generic wrappers of these entities, and the name of the entity will show up as `div/@type`, prefixed with "requirement-" in this instance

So instead of `<description>`, you will get `<div type="requirement-description">`

**Comment by Intelligent2013** [comment]
Done.
