### ISSUE TITLE
"git tag, git push" is not idiot proof

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#432]
I have been told by @ronaldtse to stop using rake release and start using git tag and git push

Unlike rake release, this lets me do git tag and git push without checking that the version of the gem has been updated.

This means git tag, git push is not idiot proof.

Why yes, I am the idiot. And if you fail to put failsafes around me, you're the ones suffering from it.

Some sort of feedback mechanism is needed so that I cannot push to origin without the version being confirmed as updated. Like rake release was giving me.

**Comment by opoudjis** [comment]
In addition:

https://github.com/metanorma/isodoc/actions/runs/2990877739

````
Error: The process '/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle' failed with exit code 6
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:6023:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:6006:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5900:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
````

I simply CANNOT have releases to rubygems fail. That is not acceptable. The release process takes hours upon hours as is, and it depends on the gem updates being released in rapid succession. Anything that gets in the way of rubygems updating is simply not fit for purpose.

**Comment by ronaldtse** [comment]
> I cannot push to origin without the version being confirmed as updated. Like rake release was giving me.

You cannot push a tag if it was already created.

**Comment by ronaldtse** [comment]
When a gem is released, Rubygems sends an email notifying.

**Comment by ronaldtse** [comment]
When a release fails, you get an email from GHA.

**Comment by CAMOBAP** [comment]
> In addition:
> 
> https://github.com/metanorma/isodoc/actions/runs/2990877739
> 
> ```
> Error: The process '/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle' failed with exit code 6
>     at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:6023:25)
>     at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:6006:18)
>     at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5900:27)
>     at ChildProcess.emit (node:events:390:28)
>     at maybeClose (node:internal/child_process:1064:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
> ```
> 
> I simply CANNOT have releases to rubygems fail. That is not acceptable. The release process takes hours upon hours as is, and it depends on the gem updates being released in rapid succession. Anything that gets in the way of rubygems updating is simply not fit for purpose.

I can check if the gem version was released before push just to avoid those fails

----

But as far as I understand this will not resolve the main issue for @opoudjis (i.e. releases becomes longer)

And here I don't have a strict opinion:
 - From one side we cannot do a release without tests before
 - From another side, I don't want to @opoudjis suffer. And waited hours on a new release to pass

Some time ago me and @opoudjis already discussed (in Skype) some potential to automate it a bit more: i.e. if gem-x is released we are ok to start a release of some gem-y. In our case, it can be metanorma and metanorma-cli gems

As far as I understood, this approach also does not very fit our needs

@ronaldtse @opoudjis I just want to say that really want to make the release process better for all of us. If you have any ides how we can do this, let's discuss it here

**Comment by ronaldtse** [comment]
@CAMOBAP The real problem here is that @opoudjis has a circular dependency, which is causing Bundler to fail (because it can't find the gems), and that even all the tests are failing. I do not know of a solution that can work with circular dependencies.

I maintain that the correct way of doing releases is:
1. All tests pass
2. Releases are made after tests pass

**Comment by ronaldtse** [comment]
To simplify the problem, there are occasions where two gems in development need to be tested against each other, and that need to be released together.

One way that it happens is that:

1. Two gems get developed in branches (in PRs), and there is a `Gemfile.devel` that points to each other's branches, so tests pass.
2. When both PRs are merged, the `Gemfile.devel` points to the `main` branches of each other, so tests pass.
3. When the gems are to be released, the existence of the `Gemfile.devel` is used during Bundler, which allows tests to pass, and then the gems can be released (assuming there is NO gemspec circular dependency)

NOTE: a circular gemspec dependency cannot exist under any circumstance.

@CAMOBAP am I missing anything here?

**Comment by ronaldtse** [comment]
In addition, perhaps the release action should not use bundler:
https://github.com/metanorma/ci/blob/9c922842fe85153304958897a7fac52b06597749/.github/workflows/rubygems-release.yml#L34

This line should be removed in order to support pushing gems that have dependencies that are not met immediately.

**Comment by ronaldtse** [comment]
I've removed that line (metanorma/ci#93) and the release worked.

We should probably also use Google's "Release Please Action" (see https://andrewm.codes/blog/automating-ruby-gem-releases-with-github-actions/) for automatic version increments. We will need to adopt the "conventional commits" commit message convention (`fix:`, `feat:`, `feat!:`, `chore:`) for auto versions.

**Comment by CAMOBAP** [comment]
> 2. When both PRs are merged, the Gemfile.devel points to the main branches of each other, so tests pass.

According to my understanding original idea for `Gemfile.devel` was to use them only for PRs and not commit it to `main` branch so tests should fail at this point too. I think if we are going to release with `Gemfile.devel` we need to define places when `Gemfile.devel` will be removed from the repo, and this will make release longer also.

I think generally circular dependencies are a bad sign. I'm not in the context but is there really no chance to break this circular dependency?

**Comment by ronaldtse** [comment]
> I think generally circular dependencies are a bad sign. I'm not in the context but is there really no chance to break this circular dependency?

I fully agree circular dependencies are bad. But this problem also happens with there is a gem ("gem one") that relies on another gem ("gem two")'s git functionality.

1. Gem two implements a feature that Gem one depends on. This function is implemented in Git but not yet released.
2. Gem one's tests which depends on the Git Gem two will fail, until Gem two is released.

**Comment by opoudjis** [comment]
Which are the dependencies in question: mn-requirements is tested by invoking standoc and isodoc's use of it, isodoc is tested by invoking metanorma's use of it.

These were not a problem until now. They will be removed, which means that the testing of dependent functionality now has to be in the invoking gem instead of the implementing gem.

**Comment by CAMOBAP** [comment]
> But this problem also happens with there is a gem ("gem one") that relies on another gem ("gem two")'s git functionality. There is no circular dependency.

I think workflow can be something like:
1. Working on the feature for `gem1` and `gem2` (`gem1` depends on `gem2`) in feature branch `feature/1`
2. Using `Gemfile.devel` in those feature branches `feature/1` to point to GitHub
3. Once development is done:
    - Merge to `main` and release `gem2`, tests should stay green
    - Delete`Gemfile.devel` rerun CI for `feature/1`, tests should stay green because gem now downloaded from rubygems
    - Merge PR from `gem1`

> Which are the dependencies in question: mn-requirements is tested by invoking standoc and isodoc's use of it, isodoc is tested by invoking metanorma's use of it.

According to this, it looks like we should not have circular dependency at all. And `mn-requirements` depends on `isodoc` as on `development` dependency https://github.com/metanorma/mn-requirements/blob/master/mn-requirements.gemspec#L34

@opoudjis can you confirm that `mn-requirements` uses `isodoc` only for test propose?

> These were not a problem until now. They will be removed, which means that the testing of dependent functionality now has to be in the invoking gem instead of the implementing gem.

@opoudjis may I kindly ask you to explain this on some example (maybe some feature which was implemented in the past)

**Comment by opoudjis** [comment]
> @opoudjis can you confirm that mn-requirements uses isodoc only for test propose?

It does, and I am now removing those tests from mn-requirements to isodoc. mn-requirements shall have no rspec tests other than existence.

**Comment by CAMOBAP** [comment]
@opoudjis just to be on the same page is there something else that we should discuss or implement in scope of this issue?

**Comment by opoudjis** [comment]
No.

Btw, rake release can be configured not to push to rubygems, and has the failsafes I need. Closing the ticket.
