### ISSUE TITLE
Crash when normative reference items contain footnote

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#459]
(Originally from: https://github.com/metanorma/iso-10303-detached-docs/pull/131#issuecomment-1321607889 , cc @anermina)

ISO 10303-31 contained the following encoding:

```adoc
[bibliography]
== Normative references

[NOTE,type=boilerplate]
--
The following standards contain provisions which, through reference in this text,
constitute provisions of this part of <<iso_std_iso_10303_en>>. At the time of
publication, the editions indicated were valid. All standards are subject to revision,
and parties to agreements based on this part of <<iso_std_iso_10303_en>> are encouraged
to investigate the possibility of applying the most recent editions of the standards
indicated below. Members of IEC and ISO maintain registers of currently valid
International Standards.
--

* [[[ISO_IEC_8824_1,(ISO/IEC 8824-1 footnote:[To be published.])ISO/IEC 8824-1]]]

* [[[iso_std_iso_10303_1_ed_1_en,ISO 10303-1:1994]]]

* [[[ISO_10303_32,(ISO 10303-32 footnote:[To be published.])ISO 10303-32]]]
```

These particular lines caused isodoc to crash:

```
* [[[ISO_IEC_8824_1,(ISO/IEC 8824-1 footnote:[To be published.])ISO/IEC 8824-1]]]
...
* [[[ISO_10303_32,(ISO 10303-32 footnote:[To be published.])ISO 10303-32]]]
```

(The fix is at https://github.com/metanorma/iso-10303-detached-docs/pull/131/commits/7fda70f0184d0b408685d989fc51da55d81b11a5)

Crash log:
```
$ bundle exec metanorma sources/iso-10303-31/document.adoc 
...
undefined method `previous=' for nil:NilClass

        fn.children.first.previous = xdup
                         ^^^^^^^^^^^
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess_footnotes.rb:30:in `footnote_backlinks1'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess_footnotes.rb:41:in `block in footnote_backlinks'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.9-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `each_with_index'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess_footnotes.rb:38:in `footnote_backlinks'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess.rb:29:in `html_cleanup'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess.rb:16:in `toHTML'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_function/postprocess.rb:11:in `postprocess'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/convert.rb:233:in `convert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/isodoc-2.3.5/lib/isodoc/html_convert.rb:26:in `convert'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.2.3/lib/metanorma/iso/processor.rb:49:in `output'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/compile.rb:149:in `process_output_threaded'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/compile.rb:141:in `block in process_exts1'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/worker_pool.rb:9:in `loop'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/worker_pool.rb:8:in `catch'
/Users/me/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/metanorma-1.5.2/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

The obvious questions are:
* Is this semantically "correct" encoding? If we wanted to maintain content equivalence to the original publication, this might be necessary.
* Is this encoding syntax "correct"?

**Comment by ronaldtse** [comment]
This was originally reported by @anermina https://github.com/metanorma/metanorma-standoc/issues/703 . Thanks!

**Comment by ronaldtse** [comment]
For ease of reproduction I've kept the branch here:
* https://github.com/metanorma/iso-10303-detached-docs/pull/136

**Comment by opoudjis** [comment]
cc @anermina

> The obvious questions are:

> Is this semantically "correct" encoding? If we wanted to maintain content equivalence to the original publication, this might be necessary.
> Is this encoding syntax "correct"?

I do not love this syntax, but it is the one I suggested and documented, and I am going to make it work.

This issue was separate to the issue in https://github.com/metanorma/metanorma-iso/issues/873 ; it is a rendering issue, and is still there.

**Comment by opoudjis** [comment]
The error is happening because the footnote is being included in the cross-reference, and is not being processed properly: it is ending up, escaped, in the citation as

`<eref type="inline" bibitemid="ISO_10303_32" citeas="[ISO 10303-32&lt;fn reference=&quot;1&quot;&gt;&lt;p&gt;To be published.&lt;/p&gt;&#10;&lt;/fn&gt;]"/>` in Semantic XML

`<eref type="inline" bibitemid="ISO_10303_32" citeas="[ISO 10303-32&#x3c;fn reference=&quot;1&quot;&#x3e;&#x3c;p&#x3e;To be published.&#x3c;/p&#x3e;&#10;&#x3c;/fn&#x3e;]"><span class="stdpublisher">[ISO</span> <span class="stddocNumber">10303</span>-<span class="stddocPartNumber">32</span><fn reference=""/><span/>'stddocNumber'&#x3e;1</eref>`, which is completely malformed, and resulting in a bogus empty footnote. Hence the error.

There are two things to do here. I could ensure that the embedded markup in the "citeas" attribute (which isn't coping with escaped markup) is processed properly. That is reasonable to do.

The second thing though is to strip the footnote. There are cases where a footnote of a reference is repeated when it is cited, in IEEE; but that is not practice in ISO, and I do not want it to become the Metanorma default.
