### ISSUE TITLE
Reviewer's note cannot be applied to an item list

### ISSUE THREAD

**Issue by anermina** [metanorma/isodoc#472]
If a reviewer's note applies to an item list, it doesn't get rendered properly:
* Bullets get mixed up when setting anchors like in the example below.
````
[[c1]]Data can be classified as one of the following:

. Unclassified;
. Restricted;
. Confidential.[[d1]]

[reviewer=rev,from=c1,to=d1]
****
comment
****
````
![image](https://user-images.githubusercontent.com/55683568/209014601-80a44973-4045-466b-92fa-c4f4b7d16443.png)

* Comment doesn't get shown when setting anchors like in the example below.
````
[[c3]]
Data can be classified as one of the following:

. Unclassified;
. Restricted;
. Confidential.
[[d3]]

[reviewer=rev,from=c3,to=d3]
****
comment
****
````
![image](https://user-images.githubusercontent.com/55683568/209014442-392e40a9-6cb7-48c9-bd0e-ac8ab19bd246.png)

**Comment by opoudjis** [comment]
`<li>` is meant to be converted within Word processing to `<p class="ListNumber1">`. The present of the review comment introduces a `<span style="mso-comment-continuation:1">` wrapper, which is disrupting that conversion: we are ending up with

````
<span style="mso-comment-continuation:1"><li level="1" class="MsoNormal">a)<span style="mso-tab-count:1">&#xA0;</span><p class="MsoBodyText"><a name="_a1e1c074-81f1-88f8-d694-8edee4e1a918" id="_a1e1c074-81f1-88f8-d694-8edee4e1a918"></a>Unclassified;</p>
</li>
````

instead of

````
<p class="ListNumber1"><a name="_a1e1c074-81f1-88f8-d694-8edee4e1a918" id="_a1e1c074-81f1-88f8-d694-8edee4e1a918"></a>a)<span style="mso-tab-count:1">&#xA0;</span>Unclassified;</p>
````

**Comment by opoudjis** [comment]
My apologies for taking so long to get to the second issue.

The second case is simply not legal markup at the moment: the standalone line `[[d3]]` at the end of the list is attached to the next meaningful element, which is the comment itself, so the comment ends up recursive and confused.

If there is any intervening text between the comment end anchor and the comment, things are fine:

````
[[c3]]
Data can be classified as one of the following:

. Unclassified;
. Restricted;
. Confidential.

[[d3]] text
````

You are trying to get the anchor to apply up to the end of the list. For that, just put the end anchor at the end of the previous line. It's the standalone line at the end of the list that is the problem. (And that is an issue internal to Asciidoctor's own parsing—including having it attach to the next block. The bookmark is never even seen by Metanorma.)

````
[[c3]]
Data can be classified as one of the following:

. Unclassified;
. Restricted;
. Confidential.[[d3]]

[reviewer=rev,from=c3,to=d3]
****
comment
****
````
