### ISSUE TITLE
Semantic part of the presentation XML isn't not well-formed

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/isodoc#485]
Source issue: https://github.com/metanorma/metanorma-bsi/issues/200#issuecomment-1426868732

The SVG images saved by Inkscape contain the namespace `xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"`. This namespace is using as prefix for the element:
```xml
<sodipodi:namedview ...
```

Semantic part of the presentation XML contains the prefix `semantic__` added before the namespace:
```xml
<semantic__sodipodi:namedview ...
```

I.e. we have the determined namespace `sodipodi` but `semantic__sodipodi` is using further:
```xml
<semantic__svg ... xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" ...
<semantic__sodipodi:namedview
```

Error message from Edge browser:
![image](https://user-images.githubusercontent.com/5559926/218305198-4c9716ad-2b02-43af-b77e-61d25fe671bf.png)

[test.zip](https://github.com/metanorma/isodoc/files/10715818/test.zip)

`bundle exec metanorma -t bsi -x presentation test.adoc`

**Comment by opoudjis** [comment]
The most conservative thing to do here is to insert semantic__ before all xmlns prefixes within embedded Semantic XML: I *really* don't want any risk of collision between Semantic and Presentation XML.

**Comment by opoudjis** [comment]
@Intelligent2013 Please confirm solution; I've just pushed to main branch

**Comment by Intelligent2013** [comment]
I've tested on https://github.com/metanorma/isodoc/files/10715818/test.zip from the initial post and found the not expected differences (left pane - new, right pane - old xml):
![image](https://user-images.githubusercontent.com/5559926/218758777-9cad4cd0-c59c-4503-91be-9b6250168cb5.png)

`xmlns:semantic__svg` added.


`Gemfile`:
```
source "https://rubygems.org"

gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "main"
gem "metanorma-bsi", git: "https://github.com/metanorma/metanorma-bsi", branch: "fix/coverimages"
gem "relaton-bsi", git: "https://github.com/relaton/relaton-bsi", branch: "main"
gem "metanorma-cli"
```

`Gemfile.lock`:
```
GIT
  remote: https://github.com/metanorma/isodoc
  revision: 834455c18bab81549fc9dda444a0ff9e40a160ef
  branch: main
...

GIT
  remote: https://github.com/metanorma/metanorma-bsi
  revision: be4fa7444e933940235afa69bf0f8e74466214e9
  branch: fix/coverimages
,,,

**Comment by opoudjis** [comment]
@Intelligent2013 Please let me know if this is now satisfactory.

**Comment by Intelligent2013** [comment]
@opoudjis everything is ok now. Thanks!

**Comment by ronaldtse** [comment]
> I'm still going to limit the changes to tags and just two attributes; I'm going to change tag names by prefixing `semantic__` after any namespace, if one is present.

Again I look forward to the day we have `<semantic>` as a separate element.

**Comment by opoudjis** [comment]
> > I'm still going to limit the changes to tags and just two attributes; I'm going to change tag names by prefixing `semantic__` after any namespace, if one is present.
> 
> Again I look forward to the day we have `<semantic>` as a separate element.

Having the semantic and presentation elements coocur in the same document is the result of a processing constraint, the fact that the XSLT processor cannot cross-reference two documents in memory. 

So you appeal here to purity, when this change is only driven by the filthiness of tool limitations. And my own tool limitations say that, like most appeals to purity, this is not going to happen.
