### ISSUE TITLE
PDF: Move deprecated and alt term label from HTML/DOC to Presentation XML

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#501]
Follow on from https://github.com/metanorma/isodoc/issues/500

Refactor: currently the DEPRECATED: label ("deprecates" under localization-strings) is added independently in HTML/DOC and in PDF. Henceforth, it shall already be added in Presentation XML; please stop adding it in PDF. So you will be receiving

`<deprecates>DEPRECATED: blah blah</deprecates>`

and (at least in JIS)

`<admitted>ALTERNATIVE: blah blah</admitted>`

**Comment by ronaldtse** [comment]
How about separating the label name and the format?

**Comment by opoudjis** [comment]
> How about separating the label name and the format?

I already have. This is only about when the label name is interpolated into output.
