### ISSUE TITLE
Image conversion problems: postscript, emf

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#521]
No checking is being done on whether image conversions associated with SVG are succeeding.

SVG to EMF conversion has just started failing in Ubuntu and Windows.

**Comment by opoudjis** [comment]
Looks like some OSs convert filename.svg to filename.emf, and some OSs to filename.svg.emf: need to allow for both.

**Comment by ronaldtse** [comment]
@opoudjis this is an issue that we need to deal with in general for image conversion, I'm not sure if this issue should be locked within isodoc.

**Comment by opoudjis** [comment]
> @opoudjis this is an issue that we need to deal with in general for image conversion, I'm not sure if this issue should be locked within isodoc.

That's the only place I encounter it.

**Comment by ronaldtse** [comment]
@opoudjis maybe we should extract all image/file format conversion into a separate gem? We're dealing with multiple format-pairs here: PS/EPS/EMF/SVG. This abstraction allows others to work on the problem too.

**Comment by opoudjis** [comment]
Get back to me in a week.

**Comment by opoudjis** [comment]
I'm closing this issue, it's addressed now locally. For abstraction, I'll need contact with those who want it, and I'd really rather someone else do it, I have too much of a backlog chronically.

**Comment by ronaldtse** [comment]
The gem is being implemented in https://github.com/metanorma/vectory/issues/1 .
