### ISSUE TITLE
stylesheets for passthrough crashing in GHA

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#546]
The recent addition of stylesheets in Presentation XML for dealing with passthrough is resulting in unpredictable crashes in Github Actions, with null pointers.

It is possible that this is because the XSLT preprocessing (which we have not used in earnest until now) is overwriting itself:

````ruby
    def preprocess_xslt(docxml)
      extract_preprocess_xslt(docxml).each do |x|
        docxml = Nokogiri::XSLT(x).transform(docxml)
      end
      docxml
    rescue ::Error => e
      require "debug"; binding.b
    end

    def extract_preprocess_xslt(docxml)
      docxml.xpath(ns("//metanorma-extension/render/preprocess-xslt"))
        .each_with_object([]) do |x, m|
          formats = x["format"]&.split(",") || []
          !formats.empty? && !formats.include?(@format.to_s) and next
          m << x.children.to_xml
        end
    end
````

It is possible that Nokogiri's XSLT is just too memory inefficient. Investigating.

**Comment by opoudjis** [comment]
Several crashes in https://github.com/metanorma/metanorma-cli/actions/runs/6767837158 (I reran a two-week old instance.)

The single crash in isodoc https://github.com/metanorma/isodoc/actions/runs/6930558936/job/18850734025 appears to be related, it is happening right after XSLT preprocessing.

**Comment by opoudjis** [comment]
Also upgrading to Nokogiri 1.15, which fixes some XSLT crashes

**Comment by opoudjis** [comment]
@andrew2net I have just pushed a PR to upgrade to Nokogiri 1.15 to relaton-bib

**Comment by opoudjis** [comment]
@CAMOBAP I am at my wit's end, help!

I am trying to run metanorma-cli rspec with Gemfile.devel, so see if PRs to gems are fixing a memory leak issue. However, spec/metanorma_spec.rb is full of `system "metanorma ..."`, which results in complaints that bundle has not been installed. 

I have addressed the bulk of these issues locally, although I have ended up having to disable one test, in a different context: putting it in and out of context is not stopping it asking for bundle install. (If you know better than me how to make it do that, it's the test "with -r option specified loads the libary and compile document" do in spec/metanorma_spec.rb )

But the execution in GHA is still aborting: https://github.com/metanorma/metanorma-cli/actions/runs/6938467772/job/18874242510 . The GHA installer for metanorma-cli is not finding the gems I am asking it to install from Gemfile.devel

We have not before today run Gemfile.devel on metanorma-cli, but we do need to be able to.

Help!

**Comment by CAMOBAP** [comment]
@opoudjis fixed and we  have to apply this fix to all our metanorma-* where we use `Gemfile.develop`:
- use `eval_gemfile` instead eval
- reorder `eval_gemfile` and `gemspec` to be:
   ```
   ...
   eval_gemfile "Gemfile.devel" if File.exist? "Gemfile.devel"

   gemspec
   ```

**Comment by opoudjis** [comment]
> @opoudjis fixed and we have to apply this fix to all our metanorma-* where we use `Gemfile.develop`:
> 
> * use `eval_gemfile ...` instead `eval ...`

Done.

**Comment by opoudjis** [comment]
As I've said on Zulip, because I do have to make progress, and the fixes to date on metanorma-cli have not addressed the underlying issue (the correct fork of isodoc is still not being invoked when processing samples documents), I am going to release isodoc with Nokogiri 1.15, and do a new batch of releases. 

I am going to create a new ticket for metanorma-cli forking, because that issue still needs to be addressed. It certainly will be if Nokogiri 1.15 does not fix this issue.

**Comment by opoudjis** [comment]
The issue has been fixed between the loop change and the upgrade to Nokogiri 1.15. I had disabled a test in metanorma-cli that was getting stuck in the attempt to get metanorma-cli to run spec with bundle exec; will try again, now that @CAMOBAP has sidestepped the need for `bundle exec` within rspec.

**Comment by CAMOBAP** [comment]
@opoudjis to be on the same page is there anything else should be done in the scope of this ticket?

**Comment by opoudjis** [comment]
No, and thank you for all your work. Have inserted the test back in, it passed. Closing.
