### ISSUE TITLE
Do not generate EMF images unless Word output is specified

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#552]
Only the Word output requires converting SVGs into EMF files. When no Word output is requested, do not generate these EMF files which take up lots of unnecessary processing time.

This can be done in conjunction with the latest Vectory refector (ping @alexeymorozov )

```
/opt/homebrew/bin/inkscape --export-type="emf" /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20231207-286-xuuhuf.svg
2023-12-07 11:47:51.060 inkscape[867:16327601] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Checking /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20231207-286-xuuhuf.svg.emf
Converting...
/opt/homebrew/bin/inkscape --export-type="emf" /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20231207-286-8xbt5m.svg
2023-12-07 11:47:51.851 inkscape[868:16327687] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Checking /var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/image20231207-286-8xbt5m.svg.emf
...
```

**Comment by opoudjis** [comment]
This was already done in https://github.com/metanorma/metanorma-bsi/issues/446 a month ago: https://github.com/metanorma/isodoc/blob/8e5521a0d902a58e84a860e745d965e65cdec8e1/lib/isodoc/presentation_function/image.rb#L111

Just compiled mn-samples-bsi/sources/pd-19650-0, which contains SVGs. Inkspace not invoked once. Suggest you update your Metanorma.

**Comment by ronaldtse** [comment]
@opoudjis I'm using isodoc version 2.7.1, which is the latest version.

You can check this issue in https://github.com/metanorma/iso-10303-srl :

```
git clone --recurse-submodules -j2 git@github.com:metanorma/iso-10303-srl.git
cd iso-10303-srl
bundle
bundle exec metanorma documents/iso-10303-41/document.adoc
```

Then you will see inkscape processing SVG files into EMF.

**Comment by opoudjis** [comment]
OK then...

**Comment by opoudjis** [comment]
OK, I see what is going on. Word is an ISO output format, but it happens not to be invoked for this document, which means I need to pass that attribute on from the metanorma-cli call.

That's doable, but harder than what I was doing excluding it from BSI.

**Comment by opoudjis** [comment]
The mn-output-extensions need to be fed into isodoc so that it knows what formats are coming up. (SVG is converted into EMF in Presentation XML, but is only required at Word.)
