### ISSUE TITLE
Switch between general and scientific notation based on size

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#602]
In number formatting, we support notation as being one of general, scientific, engineering, or e.

It is commonplace to alternate between general and scientific notation for numbers beyond a certain size; so _30_, but _3.0 &times; 10^23^_. We are injecting numbers into Metanorma from external sources, and it would be useful to automate that switch, rather than force it in source data.

I will add three parameters to our realisation of number formatting to support this:

* `large_notation` gives an alternate notation for very large or very small numbers. So `notation=general,large_notation=scientific`. (`notation=general` remains the default, so it does not need to be given explicitly.)
* `large_notation_min` is the smallest absolute value of the number, below which large_notation should be used. Its default value is 1e-6.
* `large_notation_max` is the largest absolute value of the number, above which large_notation should be used. Its default value is 1e6.

These values do not need to be propagated to  Plurimath: they will be resolved in isodoc with its preprocessing of number formatting attributes.

**Comment by opoudjis** [comment]
Any explicit notation attribute will still end up overridden by an inherited large_notation attribute: so if I have large_notation = scientific as a formatting default, then an explicit notation=e will be ignored for a large number in favour of scientific -- unless I set large_notation = nil. That's not that big a deal, but will need to be documented.

**Comment by ronaldtse** [comment]
@opoudjis why not delegate that to Plurimath?

**Comment by opoudjis** [comment]
Because this is logic about which notation to use; I do not believe it appropriate to put such decision logic into Plurimath. Plurimath should be dealing with fixed options for simplicity.

**Comment by opoudjis** [comment]
0 should not be formatted in large_notation but in general notation.
