### ISSUE TITLE
Inkspace failing to execute in GHA Windows

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#605]
https://github.com/metanorma/isodoc/actions/runs/11497889408/job/32100135481

Have rerun with separation of two days.

**Comment by CAMOBAP** [comment]
It sounds like we fixed a similar problem in the past https://github.com/metanorma/metanorma/pull/307/files ...

**Comment by opoudjis** [comment]
@CAMOBAP I think you meant this for https://github.com/metanorma/metanorma/issues/430

**Comment by opoudjis** [comment]
I have fixed https://github.com/metanorma/metanorma/issues/430, which was my bug. This issue remains.

**Comment by opoudjis** [comment]
https://github.com/metanorma/isodoc/actions/runs/11774685150
