### ISSUE TITLE
Prevent presentation content for blocks from being added in PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#607]
In https://github.com/metanorma/isodoc/issues/606, I am moving content from being added in HTML and DOC, to being added already in Presentation XML. This means that instances where you are also needing to add that content in PDF will now become redundant. This is part of the refactoring of Presentation XML that was omitted when Presentation XML was created.

In particular:

I am adding in Presentation XML `//figure/dl/p[@keep-with-next='true']` with i18n'd content "Key". You no longer need to add "Key" as a caption of figure keys independently:

I am moving footnotes of figures into the figure key. In BSI, I am instead moving footnotes into paragraphs at the end of the figure.

I'll attach Presentation XML samples.

Update from @Intelligent2013 :
To do:
- [x] don't need to add "Key" for Figures
- [x] display footnotes from the figure key `<p keep-with-next="true">`
- [x] display footnotes from the figure key `<p keep-with-next="true">`, case for BSI
- [x] display formula label (element `name`) 'as is', no need to add parentheses around label
- [x] display term `domain` from `definition` 'as is', no need to wrap it in angle brackets
- [x] suppress display of domain for IEC, IEV documents (I assume it made in the Presentation XML already)
- [x] display quote from the new structure
- [x] display `note/name` 'as is', no need to add special characters between note and body (but still add space or tab)
- [x] don't need to add title to `definitions` or `foreword` clauses if the title is missing
- [x] display `termnote/name` 'as is', no need to add special characters between note and body (but still add space)

**Comment by opoudjis** [comment]
This is what Presentation XML now looks like in ISO for figures with keys:

````
<figure id="_85160aa4-f550-6c9d-8470-985ab1957351"><name>Figure 1</name><pre id="_b8315197-3b33-46c3-d67b-0fdd01904167">A</pre>

<p keep-with-next="true"><strong>Key<strong/></strong></p><dl id="_bdbf85ba-8b6e-a69a-2669-d459537c33a2" class="formula_dl"><dt>A</dt>
<dd><p id="_60826d5a-c9b6-cacf-8630-7454e9bc91c8">B</p>
</dd> 
<dt>C</dt>
<dd><p id="_afa6491c-9ed7-10d7-bc40-c592a58cc533">D</p>
</dd>
</dl>
</figure>
````

So you don't need to add "Key" separately.

This is what a figure with a footnote now looks like:

````
<figure id="_ed7bba63-7e12-f1dd-dfae-990f2974ce4b"><name>Figure 1</name><pre id="_b8315197-3b33-46c3-d67b-0fdd01904167">A</pre>


<p keep-with-next="true"><strong>Key<strong/></strong></p><dl class="formula_dl"><dt>a</dt><dd><p id="_832f93e3-919d-4e62-4c90-3cb93890a410">Foootnote</p>
</dd> </dl></figure>
````

This is what a figure with a footnote now looks like in BSI:

````
<figure id="_4eeba4ad-4d05-bdd9-4805-83c9d8f73108"><name>Figure 1</name><pre id="_1e601235-7663-e725-9dd9-28c83bf3d345">A</pre>


<p id="_d4bd5bb7-8b06-a762-ed9d-a233d308d8bc">A Foootnote</p>
</figure>
````

**Comment by Intelligent2013** [comment]
> I am moving footnotes of figures into the figure key. 

Question: what if the figure doesn't have the 'Key's items, then the footnote will be rendered under the caption Key in any case?
Or `Key` means _all_ artifacts relate to the figure?

> In BSI, I am instead moving footnotes into paragraphs at the end of the figure.
> `<p id="_d4bd5bb7-8b06-a762-ed9d-a233d308d8bc">A Foootnote</p>`

Currently in BSI documents, the footnotes render with smaller font size with baseline shift up, with `)` after footnote mark:

![image](https://github.com/user-attachments/assets/5728eccf-063f-40f8-b87d-7eea9250e00b)

Is there a way to allocate the footnote mark (`A`) into the tag `sup` and add the attribute `class="fn"` into the `p`. Something like this:
```xml
`<p id="_d4bd5bb7-8b06-a762-ed9d-a233d308d8bc" class="fn"><sup>A</sup> Foootnote</p>`
```

**Comment by opoudjis** [comment]
Superscripting: I can do that, yes.

If there is no Key, I create one, in Presentation XML. What was happening was, I was creating one in HTML, and never told you I was. This is ISO default behaviour (footnotes are included in the key), and it is a default behaviour I have propagated to all other flavours (because ISO was the first flavour I created). BSI is the only flavour that prescribes different behaviour.

**Comment by opoudjis** [comment]
Yeah, I see that I have implemented the wrong behaviour for BSI, and they are just normal footnotes within the figure, like for tables. Will fix.

**Comment by opoudjis** [comment]
Now getting expected behaviour in BSI.

Please keep ticket open, there will be more.

**Comment by opoudjis** [comment]
Formulas until now expect HTML and PDF independently to insert the parentheses around their label:

````
<formula id="A">
<name>4</name>
<stem>
<math/>
</stem>
</formula>
````

I am going to be doing that inserting of parentheses in Presentation XML now: it is a Presentation XML concern. However, I am going to leave `<name>` alone, and I will not be dealing with the tab and the name following the stem expression.

**Comment by opoudjis** [comment]
The term domain is injected at the start of the term definition, as "<#{domain}>". This is being done in HTML, as legacy that I never got around to undoing: it is of course necessarily a Presentation XML concern.

There will be no need for HTML and PDF to inject the domain into the term definition and wrap it in angle brackets: that will be done in Presentation XML.

So:

Semantic XML:

````
<term><preferred>natural</preferred>
<domain>mathematics</domain>
<definition><p>sequence of integers</p></definition>
</term>
````

currently HTML and PDF inject "&lt;mathematics&gt;" at the start of the first definition paragraph. That will now be done in Presentation XML:

````
<term><preferred>natural</preferred>
<definition><p>&lt;<domain>mathematics</term>&gt; sequence of integers</p></definition>
</term>
````

And I'm leaving the "domain" tag in, anticipating https://github.com/metanorma/isodoc/issues/610: Presentation XML will preserve Semantic XML markup. PDF and HTML will just ignore the tag and render its contents.

**Comment by opoudjis** [comment]
Complication: in IEC, IEV documents suppress display of domain. We will set `@hidden=true` on domain in that context.

**Comment by opoudjis** [comment]
This may well not have been used ever, but we generate a quotation attribution paragraph in HTML:

````
<quote id="_">
        <source type="inline" bibitemid="ISO7301" citeas="ISO 7301:2011"><locality type="clause"><referenceFrom>1</referenceFrom></locality>ISO&#xa0;7301:2011, Clause 1</source>
        <author>ISO</author>
        <p id="_">This International Standard gives the minimum specifications for rice (<em>Oryza sativa</em> L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).</p>
</quote>
````

to

````
<div class="Quote" id="_">
        <p id="_">This International Standard gives the minimum specifications for rice (<i>Oryza sativa</i> L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).</p>
      <p class="QuoteAttribution">&#8212; ISO, ISO&#xa0;7301:2011, Clause 1</p></div>
</div>
````

This needs to be done in Presentation XML:

````
<quote id="_">
        <p id="_">This International Standard gives the minimum specifications for rice (<em>Oryza sativa</em> L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).</p>
      <attribution><p>&#8212; <author>ISO</author>,  <eref type="inline" bibitemid="ISO7301" citeas="ISO 7301:2011"><locality type="clause"><referenceFrom>1</referenceFrom></locality>ISO&#xa0;7301:2011, Clause 1</eref></p></attribution>
      </quote>
````

As above, the author wrapper is ignored; the source wrapper is converted to eref—there is no good reason to maintain the distinction. The attribution wrapper may be used for styling, but is otherwise ignored.

**Comment by opoudjis** [comment]
IEEE and ITU defined in HTML code the delimiter between the note label (NOTE, NOTE 1) and the note contents. That's an antipattern: this was supposed to be resolved in Presentation XML. The experiment around how to do so with OGC led to the unfortunate issue of https://github.com/metanorma/isodoc/issues/609, and will instead lead to explicit markup of delimiters in Presentation XML in https://github.com/metanorma/isodoc/issues/611

So in all of IEEE, ITU, OGC, we have currently:

Semantic XML:

````
<note id="note1">
        <p id="_f06fd0d1-a203-4f3d-a515-0bdba0f8d83f">First note.</p>
      </note>
````

Presentation XML:

````
<note id='note1'>
              <name>NOTE 1</name>
              <p id='_'>First note.</p>
            </note>
````

HTML:

````
 <div id='note1' class='Note'>
              <p><span class='note_label'>NOTE 1&#x2014;</span>First note.</p>
            </div>
````

Instead, we will have the Presentation XML be:

````
<note id='note1'>
              <name>NOTE 1&#x2014;</name>
              <p id='_'>First note.</p>
            </note>
````

Ultimately but not yet, that will be:

````
<note id='note1'>
              <name>NOTE <autonum>1</autonum><autonum-delim>&#x2014;</autonum-delim></name>
              <p id='_'>First note.</p>
            </note>
````

In the case of ITU, it is `&#xa0;&#x2013;&#xa0;`, but only if the note starts with a paragraph.

So PDF and HTML should not injecting the em-dash in those formats.

Moving the label inside the paragraph for notes is NOT currently being done in Presentation XML. I may do so in the future, but this iteration is for preventing content being added in HTML and PDF, not necessarily for rearranging content.

**Comment by opoudjis** [comment]
In order for us to stay in sync before release Monday after next,  I'm pausing for you to catch up, and I will make the next batch of refactoring a new ticket and isodoc PR.

**Comment by Intelligent2013** [comment]
I've updated the initial post to remember and track changes.

**Comment by opoudjis** [comment]
HTML used to add missing titles instead of letting Presentation XML do so. There are two instances where it still does: Symbols and Forewords.

These will be populated if missing in Presentation XML: there is no need for PDF or HTML to supply missing title text here.

**Comment by opoudjis** [comment]
As with notes, the insertion of the delimiter for term notes needs to be moved to Presentation XML. So you will now be receiving:

````
               <termnote id="_" keep-with-next="true" keep-lines-together="true">
                <name>Note 1 to entry:</name>
                 <p id="_">The starch of waxy rice consists almost entirely of amylopectin. The kernels have a tendency to stick together after cooking.</p>
               </termnote>
````

And you do not need to insert the `:` yourself.

**Comment by Intelligent2013** [comment]
@opoudjis I found the issue in the **ISO** Presentation XML for figure with a footnote and key items.

Source adoc (image in https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-1234-2019/images/fig-2b.svg)
```adoc
.Title of figure
[figure]
====
image::fig-2b.svg[]

footnote:[Figure footnote]

[%key]
1:: Item 1
2:: Item 2

A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.
====
```
Presentation XML:
```xml
<figure.....
....
<p keep-with-next="true">
	<strong>Key<strong/>
	</strong>
</p>
<dl id="_e1f3ab03-53a5-15da-c4ef-36ea1423b54e" key="true" class="formula_dl">
	<dt>1</dt>
	<dt>a</dt>
	<dd>
		<p id="_31cdbbd9-65df-7a80-ba67-0d5a832ad1c9">Figure footnote</p>
	</dd>
	<dd>
		<p id="_aeccd5e3-3c7a-7049-7417-7a50e6f5ff6c">Item 1</p>
	</dd>
	<dt>2</dt>
	<dd>
		<p id="_b4a5c2ff-e83f-2b1d-60fe-2666d93c0453">Item 2</p>
	</dd>
</dl>
<p id="_66a88fe1-e0dd-fae0-3a9f-a9573cef6ba6">A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.</p>
</figure>
```

Issues:
- empty `<strong/>` after `Key`. It's not important for me, but just for your attention.
- footnote `dt` `dd` inserted between first `dt` and `dd`
- is there a way to indicate the footnote item with `class="fn"` or `class="footnote"`? Usually, footnote label (`a`) is shorter than Key Item, therefore the distance between label and text renders shorter, And second reason, footnote label should rendered with baseline shift and smaller font size.


Just FYI, current PDF rendering (last _released_ gem):
![image](https://github.com/user-attachments/assets/7ee5e110-f4a1-4db5-8e9b-d62c57123842)
Footnote renders after all items.

**Comment by Intelligent2013** [comment]
My `Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "fix/presxml-oct24"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "fix/presxml-oct24"
```

**Comment by Intelligent2013** [comment]
> Complication: in IEC, IEV documents suppress display of domain. We will set `@hidden=true` on domain in that context.

@opoudjis I don't see `@hidden=true` in the  **IEC** Presentation XML:
```xml
<definition>
<p id="_40d2f406-bec8-1256-292f-069f64776f98">&#x3c;<domain>rice</domain>&#x3e;  organic and inorganic components other than whole or broken kernels</p>
</definition>
```

adoc:
```
== Terms and definitions

=== extraneous matter
alt:[EM]
domain:[rice]

organic and inorganic components other than whole or broken kernels

[example]
Foreign seeds, husks, bran, sand, dust.
```

`Gemfile`:
```
source "https://rubygems.org"

gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "fix/presxml-oct24"
gem "metanorma-iec", git: "https://github.com/metanorma/metanorma-iec", branch: "fix/presxml-oct24"
```

And second question - if I see `<domain hidden="true">rice</domain>`, then I don't render the `domain` content at all, right?

**Comment by opoudjis** [comment]
Starting on addressing these.

For starters, the current rendering is actually a bug: the footnote is meant to be inside the key, not after the item, and that was the intent all along. This is one of those items where the HTML and PDF have gotten out of sync.

I'd noticed the `<strong/>` but decided it was too difficult to track down. I think I know where it is though.

You're right about the footnote text. I want to make it `<sup>`, which should be shrinking the font size as well as raising it. (I've just updated the HTML CSS to ensure that.) Will `<sup>` behave correctly for you?

> @opoudjis I found the issue in the **ISO** Presentation XML for figure with a footnote and key items.
> 
> Source adoc (image in https://github.com/metanorma/mn-samples-bsi/blob/main/sources/bs-1234-2019/images/fig-2b.svg)
> 
> ```
> .Title of figure
> [figure]
> ====
> image::fig-2b.svg[]
> 
> footnote:[Figure footnote]
> 
> [%key]
> 1:: Item 1
> 2:: Item 2
> 
> A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.
> ====
> ```
> 
> Presentation XML:
> 
> ```
> <figure.....
> ....
> <p keep-with-next="true">
> 	<strong>Key<strong/>
> 	</strong>
> </p>
> <dl id="_e1f3ab03-53a5-15da-c4ef-36ea1423b54e" key="true" class="formula_dl">
> 	<dt>1</dt>
> 	<dt>a</dt>
> 	<dd>
> 		<p id="_31cdbbd9-65df-7a80-ba67-0d5a832ad1c9">Figure footnote</p>
> 	</dd>
> 	<dd>
> 		<p id="_aeccd5e3-3c7a-7049-7417-7a50e6f5ff6c">Item 1</p>
> 	</dd>
> 	<dt>2</dt>
> 	<dd>
> 		<p id="_b4a5c2ff-e83f-2b1d-60fe-2666d93c0453">Item 2</p>
> 	</dd>
> </dl>
> <p id="_66a88fe1-e0dd-fae0-3a9f-a9573cef6ba6">A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.</p>
> </figure>
> ```
> 
> Issues:
> 
> * empty `<strong/>` after `Key`. It's not important for me, but just for your attention.
> * footnote `dt` `dd` inserted between first `dt` and `dd`
> * is there a way to indicate the footnote item with `class="fn"` or `class="footnote"`? Usually, footnote label (`a`) is shorter than Key Item, therefore the distance between label and text renders shorter, And second reason, footnote label should rendered with baseline shift and smaller font size.
> 
> Just FYI, current PDF rendering (last _released_ gem): ![image](https://private-user-images.githubusercontent.com/5559926/382502243-7ee5e110-f4a1-4db5-8e9b-d62c57123842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDI3MDIsIm5iZiI6MTczMDYwMjQwMiwicGF0aCI6Ii81NTU5OTI2LzM4MjUwMjI0My03ZWU1ZTExMC1mNGExLTRkYjUtOGU5Yi1kNjJjNTcxMjM4NDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMDI1MzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjFmYjhhNWQ1NThkOWQyNWNiYjhkOWZmYmY5OTdhMzllZGNkYTdiOGM3NTU3YzZkYjlhM2I5NGIyZDU0MzgxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TuCuOYe2Tq431kLPTAsGhPbggV1D7YCEoU8WVyMlY7A) Footnote renders after all items.

**Comment by opoudjis** [comment]
Testing with two footnotes:

````asciidoc
== Scope

.Title of figure
[figure]
====
....
AA
....

footnote:[Figure footnote]

footnote:[Second Figure footnote]

[%key]
1:: Item 1
2:: Item 2

A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.
====
````

Output:

````xml
<figure id="_dfec8fce-11df-f58d-970c-da998d8a4caa">
<name>Figure 1 — Title of figure</name>
<pre id="_6dcba68c-ec85-8d55-5d2e-67c72eab70f1">AA</pre>





<p keep-with-next="true"><strong>Key</strong></p>
<dl id="_e1f3ab03-53a5-15da-c4ef-36ea1423b54e" key="true" class="formula_dl"><dt><sup>a</sup></dt>
<dd><p id="_0bfc5c0d-0322-fcdc-67f0-21c50db3e89f">Figure footnote</p>
</dd><dt><sup>b</sup></dt>
<dd><p id="_d0c7d06e-af59-036e-c1d7-85e30e362003">Second Figure footnote</p>
</dd><dt>1</dt>
<dd><p id="_aeccd5e3-3c7a-7049-7417-7a50e6f5ff6c">Item 1</p>
</dd>
<dt>2</dt>
<dd><p id="_b4a5c2ff-e83f-2b1d-60fe-2666d93c0453">Item 2</p>
</dd>
</dl>

<p id="_66a88fe1-e0dd-fae0-3a9f-a9573cef6ba6">A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.</p>
</figure>
````

**Comment by opoudjis** [comment]
> And second question - if I see <domain hidden="true">rice</domain>, then I don't render the domain content at all, right?

Correct, my intention is to make that a general design pattern for Presentation XML: if a Semantic XML element has been moved to a Presentation element, we will leave it alone where it is (because the brief now is to preserve the Semantic XML intact where possible, so that it can be passed back out to external processing). But we will signal that it is to be rendered in the new not the old location, by putting a hidden flag on it.

The intention in that IEC example was, it is NOT the `term/definition/domain` element that is hidden. It is the original instance of `term/domain`, which until now I have been hiding from Presentation XML. 

But I came to that conclusion after I had already implemented this, so you're not seeing it yet. (Ronald, this was the latest discussion we had.) Fixing:

````xml

<term id="term-_lt_rice_gt_-extraneous-matter">
<name>1.1</name>
<preferred><strong>extraneous matter</strong></preferred><admitted>EM</admitted>

<domain hidden="true">rice</domain>

<definition><p id="_40d2f406-bec8-1256-292f-069f64776f98">&#x3c;<domain>rice</domain>&#x3e;  organic and inorganic components other than whole or broken kernels</p></definition>

 <termexample id="_9ef9a58e-7cc5-f6e1-93a2-57537107ae9b"><name>EXAMPLE</name><p id="_125f86e5-c156-e0e3-baae-1c6355e8c531">Foreign seeds, husks, bran, sand, dust.</p>
</termexample></term>
</terms>
````

It is quite possible that, in order to keep the Presentation XML grammar constrained, I will use not `term/definition/domain`, but `term/definition/span[@class = 'fmt-domain']`: I don't want to add every single possible Semantic XML inline element to the Presentation XML inline grammar, and the intention is to extract the  inserted objects from Presentation XML for different processing, not to reconstruct the Semantic XML out of the preformatted element:

````xml
<definition><p id="_40d2f406-bec8-1256-292f-069f64776f98">&#x3c;<span class="fmt-domain">rice</span>&#x3e;  organic and inorganic components other than whole or broken kernels</p></definition>
````


But that decision is being deferred to https://github.com/metanorma/isodoc/issues/610 . For now, that is what you are getting.

**Comment by Intelligent2013** [comment]
> Will `<sup>` behave correctly for you?

Yes, if I see `dt/p/sup` alone, that it means for me that key item text `a` is footnote label:
```xml
<dt><p><sup>a</sup></p></dt>
<dd><p id="_0bfc5c0d-0322-fcdc-67f0-21c50db3e89f">Figure footnote</p>
</dd>
```
I think it's enough, don't need to add `class="fn"` or `class="footnote"` as I've wrote above.

**Comment by opoudjis** [comment]
I have done a refactor as a result of which `<span>` notation, which was showing up under `biblio-tag` and `eref` in HTML/DOC (DOC needs it in ISO), is now moving to Presentation XML. Can I confirm that you won't have trouble with just ignoring the `span` wrapper inside `biblio-tag`, and processing their content?

````
            <biblio-tag>
               <span class="stdpublisher">ISO </span>
               <span class="stddocNumber">712</span>
               ,
            </biblio-tag>
````

**Comment by Intelligent2013** [comment]
> Can I confirm that you won't have trouble with just ignoring the `span` wrapper inside `biblio-tag`, and processing their content?

no problem.

Another issue occurs today. I'm trying to generate the Presentation XML for adoc:
```
= Rice model
:docnumber: 17301
:tc-docnumber: 17301
:partnumber: 1
:edition: 2
:revdate: 2016-05-01
:copyright-year: 2016
:language: en
:title-intro-en: Cereals and pulses
:title-main-en: Specifications and test methods
:title-part-en: Rice (CD)
:title-intro-fr: Céréales et légumineuses
:title-main-fr: Spécification et méthodes d'essai
:title-part-fr: Riz (CD)
:doctype: international-standard
:docstage: 60
:docsubstage: 00
:mn-output-extensions: xml,html,doc,pdf
:local-cache-only:

== Test Figures Key

.Title of figure
[figure]
====
....
AA
....

footnote:[Figure footnote]

footnote:[Second Figure footnote]

[%key]
1:: Item 1
2:: Item 2

A complete abuse of notation random paragraph inside of a figure, instead of putting provisions where they belong.
====


== Terms and definitions

=== extraneous matter
alt:[EM]
domain:[rice]

organic and inorganic components other than whole or broken kernels

[example]
Foreign seeds, husks, bran, sand, dust.


== Formula label

Express the mass fraction of each defect using <<formulaA-1>>:

[[formulaA-1,A.1]]
[stem]
++++
w = (m_D) / (m_s)
++++

where

stem:[w]:: is the mass fraction of grains with a particular defect in the test sample;
stem:[m_D]:: is the mass, in grams, of grains with that defect;
stem:[m_S]:: is the mass, in grams, of the test sample.

== Quote example

Text text text

[quote, ISO, "ISO7301,clause 1"]
_____
This International Standard gives the minimum specifications for rice (_Oryza sativa_ L.) which is subject to international trade. It is applicable to the following types: husked rice and milled rice, parboiled or not, intended for direct human consumption. It is neither applicable to other products derived from rice, nor to waxy rice (glutinous rice).
_____


[bibliography]
== Bibliography

* [[[ISO7301,ISO 7301:2011]]], _Rice -- Specification_

```

`bundle exec metanorma -t iso -x presentation iso_new.adoc` fails:
```
C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_function/refs.rb:1:in `require_relative': cannot load such file -- C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_function/docid (LoadError)
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_function/refs.rb:1:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_function/section.rb:1:in `require_relative'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_function/section.rb:1:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_xml_convert.rb:9:in `require_relative'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc/presentation_xml_convert.rb:9:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc.rb:22:in `require'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/bundler/gems/isodoc-99c304cb9f44/lib/isodoc.rb:22:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.7/lib/metanorma/collection/renderer/renderer.rb:1:in `require'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.7/lib/metanorma/collection/renderer/renderer.rb:1:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.7/lib/metanorma.rb:18:in `require'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-2.0.7/lib/metanorma.rb:18:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.11/lib/metanorma/cli.rb:3:in `require'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.11/lib/metanorma/cli.rb:3:in `<top (required)>'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.11/exe/metanorma:24:in `require'
        from C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.10.11/exe/metanorma:24:in `<top (required)>'
        from C:/tools/ruby31/bin/metanorma:25:in `load'
        from C:/tools/ruby31/bin/metanorma:25:in `<main>'
```


My `Gemfile`:
source "https://rubygems.org"
```
gem "metanorma-cli"
gem "isodoc", git: "https://github.com/metanorma/isodoc", branch: "fix/presxml-oct24"
gem "metanorma-iso", git: "https://github.com/metanorma/metanorma-iso", branch: "fix/presxml-oct24"
gem "metanorma-iec", git: "https://github.com/metanorma/metanorma-iec", branch: "fix/presxml-oct24"
```

**Comment by Intelligent2013** [comment]
Regarding `note/name` and `termnote/name`, currently in the PDF these characters render after the `name`.
- `note/name`:
  - **IEEE** `&#x2014;` (em dash)
  - **IHO**, **JCGM** (hard-coded in XML already), **OGC** (in XML already via XSLT block in Presentation XML), **Ribose** `:` (colon)
  - **ITU**, **NIST** ` &#x2013; ` (en dash with spaces around)
- `termnote/name`:
  - **IEEE** `&#x2014;` (em dash)
  - **ISO**, **IEC**, **JCGM** (hard-coded in XML already), **OGC**, **Ribose** `:` (colon)
  - **ITU**, **NIST**` &#x2013; ` (en dash with spaces around)

I.e. for **ISO**, **IEC** I don't display `:` after `note/name`. And three characters 'em dash', 'en dash with spaces' and 'colon' are using in the different flavors.

**Comment by Intelligent2013** [comment]
> don't need to add title to `definitions` or `foreword` clauses if the title is missing

No changes, the XSLTs don't add these titles.

**Comment by opoudjis** [comment]
> Another issue occurs today. I'm trying to generate the Presentation XML for adoc:

While the refactoring in fix/refactor-xrefs-oct24 succeeded rapidly, I'ver merged it into fix/presxml-oct24 prematurely; there is a lot to clean up downstream, though none of it should be resulting in different output in Presentation XML. (It already has in ISO, but I regard that as something to refactor away.) So I am unmerging fix/refactor-xrefs-oct24, until all the downstream gems are tested.

**Comment by opoudjis** [comment]
> Regarding `note/name` and `termnote/name`, currently in the PDF these characters render after the `name`.
> 
> * `note/name`:
>   
>   * **IEEE** `&#x2014;` (em dash)
>   * **IHO**, **JCGM** (hard-coded in XML already), **OGC** (in XML already via XSLT block in Presentation XML), **Ribose** `:` (colon)
>   * **ITU**, **NIST** `&#x2013;` (en dash with spaces around)
> * `termnote/name`:
>   
>   * **IEEE** `&#x2014;` (em dash)
>   * **ISO**, **IEC**, **JCGM** (hard-coded in XML already), **OGC**, **Ribose** `:` (colon)
>   * **ITU**, **NIST**`&#x2013;` (en dash with spaces around)
> 
> I.e. for **ISO**, **IEC** I don't display `:` after `note/name`. And three characters 'em dash', 'en dash with spaces' and 'colon' are using in the different flavors.

I do not understand what you are saying. Are you saying that in all of IEEE, RIbose, ITU, NIST, PDF is adding delimiters independently of the Presentation XML?

**Comment by Intelligent2013** [comment]
> I do not understand what you are saying. Are you saying that in all of IEEE, RIbose, ITU, NIST, PDF is adding delimiters independently of the Presentation XML?

I mean that a different characters (and none) are using after `note` displaying,

In your examples (see above) only `&#x2014;` is using in `note/name`:
```
<note id='note1'>
              <name>NOTE 1&#x2014;</name>
              <p id='_'>First note.</p>
            </note>
```

and `colon` in `termnote/name`
```xml
<termnote id="_" keep-with-next="true" keep-lines-together="true">
                <name>Note 1 to entry:</name>
                 <p id="_">The starch of waxy rice consists almost entirely of amylopectin. The kernels have a tendency to stick together after cooking.</p>
               </termnote>
```
are using. If they are just example, then ok. If they are constants for _all_ flavors, then we'll get the different results in PDF than currently. I don't know what we should get - the unified rendering for all flavors, or as currently, the individual rendering...

**Comment by opoudjis** [comment]
The current situation, where PDF is inserting delimiters for some flavours and not for others, is not acceptable, because it is allowing for inconsistencies between formats, and because it defeats the purpose of having a Presentation XML to begin with. The point of this refactor is to minimise repeating work between formats, so that new  implementations of formats (such as Firelight) are having to duplicate effort. The subsequent step to be taken in https://github.com/metanorma/isodoc/issues/611, of semantically annotating any such delimiters, is so that any downstream renderers choosing to alter rendering do so with an understanding of what they are changing, which can be configured.

These are not just examples. These are how this is going to work from now on. So in all those cases, yes, those delimiters need to be inserted by Presentation XML, and not by HTML and PDF independently, and I will be adding them to the Presentation XML (once I finish my current round of testing.)

**Comment by opoudjis** [comment]
* IEEE: I have already moved the `&#x2014'` inside the Presentation XML name for termnote and note. You need to stop doing adding it.
* Ribose: I have already moved the ": " inside the Presentation XML name for termnote. I am now moving the ": " inside the Presentation XML for note. You need to stop doing adding it.
* OGC: I have already moved the ": " inside the Presentation XML name for note and termnote. You need to stop doing adding it.
* ITU: I have already moved the " `&#x2013;` " inside the Presentation XML name for note and termnote. You need to stop doing adding it.
* NIST:  I am now moving the " `&#x2013;` " inside the Presentation XML name for note and termnote. You need to stop doing adding it.

**Comment by opoudjis** [comment]
In fact, in ISO after xrefs refactoring moving all docidentifier processing to Presentation XML, what is happening is that the standards annotation is being applied *more* consistently than before, including in biblio-tag (i.e. in references listings). For now, I am going to treat this as a feature not a bug.

**Comment by opoudjis** [comment]
note/name and termnote/name generation is being updated for all flavours: do NOT add ":" for any of them.

In BSI, footnotes are NOT moved inside the Key. That was an initial error on my part.

**Comment by opoudjis** [comment]
@Intelligent2013 Should I post the issues I've just broken down in https://github.com/metanorma/isodoc/issues/606#issuecomment-2456811702 as a new issue for you?

**Comment by Intelligent2013** [comment]
> @Intelligent2013 Should I post the issues I've just broken down in [#606 (comment)](https://github.com/metanorma/isodoc/issues/606#issuecomment-2456811702) as a new issue for you?

I'm going to merge the XSLT updates for the tasks from the initial post until the end of this week (before next Monday release), and then close this ticket. For the updates for after the next release (after next Monday release)  I need a new ticket. If you plan to include the updates from https://github.com/metanorma/isodoc/issues/606#issuecomment-2456811702 in the Monday release, then I'm ready to update XSLT also on this week, but give me 1 working (not weekend) day.
