### ISSUE TITLE
Move presentation functionality for HTML to Presentation XML, individual flavours: PDF

### ISSUE THREAD

**Issue by opoudjis** [metanorma/isodoc#614]
As discussed, this is the continuation of https://github.com/metanorma/isodoc/issues/607, and is the counterpart to https://github.com/metanorma/isodoc/issues/613 . I will need you to confirm existing PDF behaviour.

Continuation of https://github.com/metanorma/isodoc/issues/606

* [x] Admonition name:
  * ISO: Keep name in Presentation XML, and add em-dash to Presentation XML
  * JIS: Add em-dash to Presentation XML (why?)
  * BSI: Add "." to Presentation XML

Before:

````
<admonition id="_b1c10b4a-ec44-2044-443b-356095346b87" type="warning">
<name>admon</name>
<p id="_baae1513-5def-451a-727f-fc44ed9a724f">A</p>
</admonition>
````

After:

````
<admonition id="_b1c10b4a-ec44-2044-443b-356095346b87" type="warning">
<name>admon.</name>
<p id="_baae1513-5def-451a-727f-fc44ed9a724f">A</p>
</admonition>
````

* [x] Example names:
   * IEEE: Add ":" to  Presentation XML

Before:

````
<example id="_d9f3e188-b0d0-27dc-f00a-b0d9b159cb15"> 
<name>example name</name>
<p id="_9cefd064-b4b2-6658-5701-054bedcd09f6">A</p>
</example>
````

After:

````
<example id="_d9f3e188-b0d0-27dc-f00a-b0d9b159cb15"> 
<name>example name:</name>
<p id="_9cefd064-b4b2-6658-5701-054bedcd09f6">A</p>
</example>
````

* [x] Annex subtitles:
  * ITU: Move obligation subtitle for non-resolutions to Presentation XML

Before:

````
<annex id="_annextitle" inline-header="false" obligation="normative">
<title>Annextitle</title>
````

After:

````
<annex id="_annextitle" inline-header="false" obligation="normative">
<title>Annextitle</title>
<p>(This annex forms an integral part of this Contribution.)</p>
````

* [x] Term sources:
  * ITU: Wrap term sources  with brackets in Presentation XML, unless already wrapped (and fix current assumption that termsource/origin is preserved in Presentation XML, which it is not)
* Term designation:
  * ITU: Insert ":" after preferred

Before:

````
<term id="term-language"><preferred><expression>
<name>language</name>
</expression>
</preferred>
<definition><verbal-definition><p id="_11e12e77-315b-a5a4-d550-5c3758e6f3d2">a means of communication</p></verbal-definition></definition>
<termsource status="identical" type="authoritative">[SOURCE: <xref type="inline" target="a">[ISO 639-2]</xref>]</termsource>
</term>
````

After:

````
<term id="term-language"><preferred><expression>
<name>language</name>
</expression>:
</preferred>
<definition><verbal-definition><p id="_11e12e77-315b-a5a4-d550-5c3758e6f3d2">a means of communication</p></verbal-definition></definition>
<termsource status="identical" type="authoritative"><xref type="inline" target="a">[ISO 639-2]</xref></termsource>
</term>
````

* [x] Table & figure footnotes:
  * ITU: insert ")" after the footnote reference number in text and in the footnote  reference number in the footnote

Before:

````
<table id="_25127a95-78ea-5048-8b95-a3448d203f0b"><name>Table A.1</name><tbody><tr><td valign="top" align="left">A</td>
<td valign="top" align="left">b.<fn reference="a"><p id="_5474b7ae-7f64-f546-7268-0e110005ff52">X</p>
</fn></td>
</tr></tbody>
</table>
````

After:

````
<table id="_25127a95-78ea-5048-8b95-a3448d203f0b"><name>Table A.1</name><tbody><tr><td valign="top" align="left">A</td>
<td valign="top" align="left">b.<fn reference="a)"><p id="_5474b7ae-7f64-f546-7268-0e110005ff52">X</p>
</fn></td>
</tr></tbody>
</table>
````

* [x] Table & figure footnotes:
  * JIS: insert Japanese "table footnote" and ")" around the footnote  reference number in the footnote (fix: needs to be also be ")" in the text in HTML)

Same before and after for as with ITU

Note that there is a distinction in what actually gets rendered:

````
<table>
<tbody><tr>
<td>A</td>
 <td>b.<sup>a)</sup></td>
</tr></tbody>
<tfoot>
<tr><td>注<sup>a)</sup> X</td></tr>
</tfoot>
</table>
````

The footnote reference under tbody is "a)", the footnote itself under tfoot is "FOOTNOTE a) X". We do not have a mechanism for expanding that out in Presentation XML into a preformatted footnote, that is left to the renderer, and the assumption until now has been that the footnote itself starts with just the footnote reference.

We are in the future going to introduce preformatted versions of Semantic XML, and we would deal with this then as 

````
<fn reference="a)" id="FN1">
<p id="_5474b7ae-7f64-f546-7268-0e110005ff52">X</p>
</fn>
<fmt-fn reference="a)" target="FN1">
<p id="_5474b7ae-7f64-f546-7268-0e110005ff52"><span class="autonum-delim">注</span><sup>a)</sup> X</p>
</fn>
````

—so that I will hand down from Presentation XML the preformatted footnote body. But not yet.

Leaving the Plateau ideographic text alone. Leaving BIPM and ISO indexes alone.

**Comment by opoudjis** [comment]
Thank you. I haven't implemented anything in Presentation XML yet, that is tonight, but it looks like the PDF will be ready to go when I do!

**Comment by opoudjis** [comment]
Clarified behaviour on Admonitions:

In ISO, BSI, JIS: if admonition/name is followed by admonition/p, render the contents of name and a tab in the first paragraph: so

````
<admonition>
<name>WARNING:</name>
<p>first paragraph</p>
...
````

rendered as:

````
<p>WARNING: first paragraph</p>
...
````

If the first element after `name` is not `p` in ISO JIS BSI, and in every other flavour, render the name in its own paragraph:

````
<admonition>
<name>WARNING</name>
<ol>
  <li>first paragraph</li>
</ol>
...
````

rendered as:

````
<p>WARNING</p>
<ol>
  <li>first paragraph</li>
</ol>
...
````

Presentation XML will work out whether to insert the delimiter or not. The renderer works out whether to put the name on its own paragraph or not. (I was preempting that decision, by moving the name inside the paragraph. For now, I am not going to be doing that, but I may come back to that in the future, once we have more consistently separated Presentation from Semantic XML again.)

We do this kind of thing with notes in rendering; we are extending that behaviour to admonitions (which are, after all, kinds of notes). This is to allow rendering such as:

____

NOTE: blah blah blah

CAUTION — blah blah blah
____

**Comment by opoudjis** [comment]
IEEE Examples: not only am I adding ":" to example name, but I am italicising it, which I was not doing before.

**Comment by opoudjis** [comment]
IEEE term examples: styling them the same as normal examples in Presentation XML

**Comment by opoudjis** [comment]
I have finished work on https://github.com/metanorma/isodoc/issues/613 ; could you please confirm that it is has what you expect to find?

**Comment by Intelligent2013** [comment]
Additional task for me:
- [ ] IEEE term examples: styling them the same as normal examples in Presentation XML

**Comment by Intelligent2013** [comment]
> I have finished work on #613 ; could you please confirm that it is has what you expect to find?

Yes, confirm. Thanks.
XSLT are ready to merge in https://github.com/metanorma/mn-native-pdf/pull/763.
