### ISSUE TITLE
Move all code relating to forcing additional line brakes inside MathML away from XML

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#616]
> * The conversion of MathML linebreaks to two split up MathML expressions, needed for DOC, will be moved to html2doc as preliminary, DOC-specific processing before conversion to MathML

> This is PDF-specific, not DOC-specific processing. I'm going to handle this as passthrough once https://github.com/metanorma/mn-native-pdf/issues/764 is done: so

isodoc/lib/isodoc/presentation_function/math.rb

````
def mathml_linebreak(node)
      node.at(".//*/@linebreak") or return
      m = Plurimath::Math.parse(node.to_xml, :mathml)
        .to_mathml(split_on_linebreak: true)
      ret = Nokogiri::XML("<m>#{m}</m>").root
      ret.elements.each_with_index do |e, i| 
        i.zero? or e.previous = "<br/>"
      end
      node.replace(<<~OUTPUT)
        <math-with-linebreak>#{ret.children}</math-with-linebreak>
        <math-no-linebreak>#{node.to_xml}</math-no-linebreak>
      OUTPUT
    end
````

The final expression needs to be instead:

````
      node.replace(<<~OUTPUT)
        <passthrough formats=",pdf,">#{ret.children}</passthrough>
        <passthrough formats=",html,doc,">#{node.to_xml}</passthrough>
      OUTPUT
````

> Later on we may need to preserve Semantic XML MathML along with Presentation XML MathML, but math-no-linebreak is the canonical, Semantic version of the MathML. (PDF is forcing us to break the MathML into two different expressions on linebreak.)

Since this is a PDF specific problem, we will only have normal MathML in XML. 

We need to remove all PDF-specific math processing away from the Ruby stack and have this bug (presumably a rendering bug in Batik) addressed as close to the problem as possible. 

Ping @intelligent2013

 
_Originally posted by @opoudjis in https://github.com/metanorma/isodoc/issues/609#issuecomment-2461948436_

**Comment by opoudjis** [comment]
@Intelligent2013 Obviously this is for the next fortnightly sprint of Presentation XML refactoring, starting Monday.

**Comment by Intelligent2013** [comment]
This is a jEuclid issue. I don't believe that I can solve this jEuclid issue in two weeks, or at all.

**Comment by opoudjis** [comment]
The request is not that you solve the rendering issue, because you've been clear that you can't, but that you do in XSLT what is currently being done in Plurimath through the `--split-on-linebreak` attribute: breaking up  MathML expressions at `@linebreak` into separate expressions, and then rendering them. So from https://github.com/plurimath/plurimath/issues/179:

````
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <mo>&#x230a;</mo>
      <mrow>
        <mi>&#x3c3;</mi>
        <mo linebreak="newline"/>
        <mi>&#x3b8;</mi>
      </mrow>
      <mo>&#x230b;</mo>
    </mrow>
  </mstyle>
</math>
````

would thus go to:

````
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <mo>&#x230a;</mo>
      <mrow>
        <mi>&#x3c3;</mi>
       </mrow>
  </mstyle>
</math>
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">
    <mrow>
      <mrow>
        <mi>&#x3b8;</mi>
      </mrow>
      <mo>&#x230b;</mo>
    </mrow>
  </mstyle>
</math>
````

That is what I get Plurimath to do currently, before passing the XML to you; @ronaldtse ’s expectation is that I do not manipulate the XML, and that therefore that gets done by the XSLT.

**Comment by Intelligent2013** [comment]
XSLT updated.

**Comment by opoudjis** [comment]
I didn't expect you to get this done for this release! Thank you very much!
