### ISSUE TITLE
Add automatic translation for the `and` keyword to Japanese

### ISSUE THREAD

**Issue by anermina** [metanorma/isodoc#624]
When using `<<a;and!b>>` syntax with the document attribute set to Japanese (`:language: ja`), the word `and` is not translated.

The original (left) and the generated (right):
![image](https://github.com/user-attachments/assets/1c464396-e6ee-4070-bb47-59b5a0a21e55)

This works properly for French, Russian and Chinese.

**Comment by opoudjis** [comment]
In fact, I've already fixed this as part of the Presentation XML refactoring I've been doing, and it will be included in this Monday's release:

````
binary_and: "%1 <conn>および</conn> %2"
````

If that *isn't* the Japanese for "and", someone will need to tell me.

**Comment by ronaldtse** [comment]
For this particular instance, it would be better to encode the two references separately because I think there can be multiple ways of specifying “and” in Japanese.

**Comment by ronaldtse** [comment]
@opoudjis as you can see, the words for “and” is different from what you have encoded.

**Comment by ronaldtse** [comment]
It would probably be wise to allow the user/flavor to update those connectives in attributes.

**Comment by opoudjis** [comment]
> It would probably be wise to allow the user/flavor to update those connectives in attributes.

I reject the notion that the word for "and" in Japanese is going to vary from one document to the next, and that it is any business of the user or flavour to specify a different word for "and" in JIS and in Plateau. It is embarrassing to even hear it suggested.

If the word for "and" is going to vary from one instance to the next, then very clearly, there should be no using of machine-generated "and" to begin with.

I make no apologies for the fact that I do not know Japanese, and am trying to extrapolate from Google Translate. If you want a different word, PROVIDE IT. And **NOT IN A SCREENSHOT**.

Further Google Translate manipulation shows that 及び and および are two different ways of writing *oyobi*, one with a Kanji, one all katakana. I have no idea why Google Translate went with the phonetic spelling, and it's not my concern to. I am switching to 及び, and closing this ticket.

**Comment by opoudjis** [comment]
Note that  we already have the ability to add an override internationalisation file to a document, which could include alternate text for "and". But varying the wording for "and" is a sign that something has gone catastrophically wrong.
