### ISSUE TITLE
Equation numbering and referencing in Japanese documents

### ISSUE THREAD

**Issue by anermina** [metanorma/isodoc#625]
Equation (1) in the original TAS 0057 document (Japanese version) is written as "(1)式", whereas Metanorma outputs it as "式 (1)."

Similarly, the equation is numbered as "(1)式" in the original document, but Metanorma produces it as "(1)".

Since this is, unfortunately, the only example of a numbered equation I have encountered in the documents written in Japanese, this ticket has been opened to address the correct numbering and referencing.
@ronaldtse could you please check? 

Original:
![image](https://github.com/user-attachments/assets/1d6598e0-3f23-48e3-83c4-b977eba14834)

Generated:
![image](https://github.com/user-attachments/assets/23957a86-40a0-4482-ace8-6f0ad808b63a)

**Comment by ronaldtse** [comment]
We need to check with JIS Z 8301 to confirm proper practice. While the JIS-industry-derivatives may follow different practices, they probably mostly adopt JIS rules.

**Comment by anermina** [comment]
Thank you @ronaldtse!

According to the JIS Z 8301 specification for equations, the Metanorma output is correct.

Below is the translation of the relevant part of the standard:
````
27.3 Numbering and classification

When formulas need to be cited or referred to, they shall be numbered with Arabic numerals in parentheses for each body and each annex, except that in annexes, the Arabic numerals shall be preceded by the Latin letter designating the annex and a period. Even if formulas are not cited or referred to, they may be numbered as necessary.

Example 1: x2 + y2 < z2 (1)
Example 2: x2 + y2 < z2 (A.1)

Numbers of formulas shall be consecutive numbers with no relation to the numbers of clauses, figures, or tables. When numbering a formula, separate numbers such as "(2a)", "(2b)", "(2.1)", "(2.2)", etc. shall not be used.

27.4 Citations and References

When numbering a formula, it is recommended that the formula number be clearly indicated in the text related to the formula, as follows: − ... is determined by formula (1).

z2＝x2＋y2 (1)

When numbering a formula, it is recommended that it be quoted or referenced in other parts of the standard. When quoting a formula number elsewhere, it should be written in the following format:
− See formula (A.2).
− See formula (3) in 3.1.
````

Whereas the original text is as follows:
![image](https://github.com/user-attachments/assets/cd3a2644-c4e5-4b73-82ec-31b4f21e5af5)

Closing this ticket, considering no changes are required.
