### ISSUE TITLE
Moving ISO-specific text to metanorma-iso

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/isodoc#94]
The "ISO Online Browsing Platform..." text now exists in https://github.com/metanorma/isodoc/blob/07b5e775a99415add74ea75c1cea500bae8d96bd/lib/isodoc-yaml/i18n-en.yaml

However, this text should be already applied in Metanorma XML. We should move textual processing to `metanorma-iso`.

`isodoc` should only concern itself with layout rendering?

**Comment by opoudjis** [comment]
The boilerplate should be moved to metanorma-iso.

Other than that, I am demoting this ticket to low priority. I reject the notion that boilerplate belongs in the XML, and that Isodoc cannot inject boilerplate. I reject even more to the constant tinkering with the Metanorma stack.

**Comment by ronaldtse** [comment]
Agreed. Good suggestion @opoudjis.

**Comment by opoudjis** [comment]
@ronaldtse Since you've moved this back to high priority, you no longer seem to agree. Do you want Terms & Definitions boilerplate to be injected into the XML now?

**Comment by ronaldtse** [comment]
Yes. The boilerplate should be apply at the Metanorma processor level, not the rendering/isodoc level. Thanks!

**Comment by opoudjis** [comment]
That applies to all boilerplate in Metanorma :-( , including Normative References.

**Comment by opoudjis** [comment]
Doing this is going to require YAML localisation in the asciidoctor to XML module, as well as the isodoc module. The downstream flavour gems will need to inherit from both YAMLs.

**Comment by opoudjis** [comment]
Moved terms & definitions boilerplate. Will now move normative references boilerplate

**Comment by ronaldtse** [comment]
Thanks @opoudjis !
